### ISSUE TITLE
feat(sd-button): add component

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#10]
- [x] prefix-slot zu icon-left
- [x] suffix-slot zu icon-right
- [x] loading state [feat: sd-button – add loading state#61](https://github.com/solid-design-system/design/issues/83)
- [x] sizes from small to sm
- [x] focus → focus-visible
- [x] solid-design-system/solid#104
- [x] solid-design-system/solid#105
