### ISSUE TITLE
feat: ✨ add sd-pagination

### ISSUE THREAD

**Issue by yoezlem** [solid-design-system/solid#1022]
## User Story
As a stakeholder of the Solid Design System, I would like to utilize sd-pagination, so that I can split up information over multiple pages.

## Documentation
https://www.figma.com/file/LiEAPa5PkSJyjkyAE9RNsi/sd-pagination-V.0.0.1?type=design&node-id=9401-33&mode=design

## DoR
- [x] Item has business value
- [x] All subtasks have been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [x] #1849
