### ISSUE TITLE
feat: ✨ add sd-datepicker

### ISSUE THREAD

**Issue by yoezlem** [solid-design-system/solid#1033]
## User Story
As a developer using the Solid Design System I want to be able to use a datepicker in the Style of Solid Design System.

## Hand-off
https://www.figma.com/file/9hJu09NkrkaPJKIe6eC5uk/sd-input%2Fsample-datepicker?type=design&node-id=18218-15792&mode=design&t=OcGUzlEnCVseAX4U-4

## Technical Information
Since we encountered limitations with the Flatpickr plugin during implementation, leaving unanswered questions and bugs unresolved (https://github.com/solid-design-system/solid/issues/273), we've decided to halt development of the datepicker component. However, during our investigation, we discovered the following plugin: https://wicky.nillia.ms/cally/. The Cally plugin offers more design and implementation flexibility, allowing us to work more harmoniously within the system. Therefore, we intend to give Cally another try.
GitHub: https://github.com/WickyNilliams/cally

#### Props
| Status | Name | Type | Default | Description |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| <ul><li>[ ] </li></ul>  | `name` | `type` | `default` | description |
| <ul><li>[ ] </li></ul>  | `name` | `type1` / `type2` | `default` | description |

#### CSS-Properties
  - [ ] `name` - description
  - [ ] `name` - description
#### Parts (besides the shoelace parts)
  - [ ] `name` - description
  - [ ] every other HTML element (depending on the HTML structure) => NOTE: if highlighting the parts in the `parts` story does not work out of the box, do not spend more effort on it but open a bug ticket to tackle it later.
#### Slots
  - [ ] `name` - description
  - [ ] `name` - description
#### Stories
  - [ ] `default` - shows the components default state
  - [ ] `slots` - shows the components slots
  - [ ] `parts` - shows the components parts
  - [ ] `name` - description
#### Samples
  - [ ] `name` - description
  - [ ] `name` - description

### Open Questions towards design
- [ ] Question1
- [ ] Question2

## Subtasks
- [ ] #567 
- [ ] Development_implementation_task
- [ ] Design_release_task

## DoR
- [ ] Item has business value
- [ ] All subtasks have been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] All subtasks have been closed
