### ISSUE TITLE
feat: ✨ add subtitle-menu & subtitles to sd-video

### ISSUE THREAD

**Issue by yoezlem** [solid-design-system/solid#1037]
## User Story
As a stakeholder of the Solid Design System, I would like to use subtitles for videos, enabling me to follow along even when I'm not listening.

## Documentation
[LINK TO FIGMA]
## Hand-off
[LINK TO FIGMA]

## Technical Information:
https://developer.mozilla.org/en-US/docs/Web/Media/Audio_and_video_delivery/Adding_captions_and_subtitles_to_HTML5_video#html_markup

#### Props
| Status | Name | Type | Default | Description |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| <ul><li>[ ] </li></ul>  | `name` | `type` | `default` | description |
| <ul><li>[ ] </li></ul>  | `name` | `type1` / `type2` | `default` | description |

#### CSS-Properties
  - [ ] `name` - description
  - [ ] `name` - description
#### Parts (besides the shoelace parts)
  - [ ] `name` - description
  - [ ] every other HTML element (depending on the HTML structure) => NOTE: if highlighting the parts in the `parts` story does not work out of the box, do not spend more effort on it but open a bug ticket to tackle it later.
#### Slots
  - [ ] `name` - description
  - [ ] `name` - description
#### Stories
  - [ ] `default` - shows the components default state
  - [ ] `slots` - shows the components slots
  - [ ] `parts` - shows the components parts
  - [ ] `name` - description
#### Samples
  - [ ] `name` - description
  - [ ] `name` - description

### Open Questions towards design
- [ ] Question1
- [ ] Question2

## Subtasks
- [ ] #1038 
- [ ] #1039 
- [ ] #1040 

## DoR
- [ ] Item has business value
- [ ] All subtasks have been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] All subtasks have been closed

**Comment by coraliefeil** [comment]
@yoezlem I’m closing this issue since we already solved it.
https://solid-design-system.fe.union-investment.de/docs/?path=/docs/templates-video--docs
