### ISSUE TITLE
ci: 👷 add log-out system icon

### ISSUE THREAD

**Issue by coraliefeil** [solid-design-system/solid#1107]
### Task

Add log-out system icon to figma library

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [x] Documentation has been created/updated (if applicable)
- [x] Implementation works successfully on `feature` branch

**Comment by van-nguyen-ht** [comment]
Icon is added to assets library
