### ISSUE TITLE
feat: ✨ add Team members inside a pattern/component as example

### ISSUE THREAD

**Issue by yoezlem** [solid-design-system/solid#1129]
## User Story
As a user of the Solid Design System, I would like to discover the Solid Design Team members subtly within a sample component, as well as enjoy an engaging and informative experience, so that the design system feels more personal and relatable, and users can learn about the team behind it in an unobtrusive and enjoyable way.

## Documentation
[LINK TO FIGMA]
## Hand-off
[LINK TO FIGMA]

#### Props
| Status | Name | Type | Default | Description |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| <ul><li>[ ] </li></ul>  | `name` | `type` | `default` | description |
| <ul><li>[ ] </li></ul>  | `name` | `type1` / `type2` | `default` | description |

#### CSS-Properties
  - [ ] `name` - description
  - [ ] `name` - description
#### Parts (besides the shoelace parts)
  - [ ] `name` - description
  - [ ] every other HTML element (depending on the HTML structure) => NOTE: if highlighting the parts in the `parts` story does not work out of the box, do not spend more effort on it but open a bug ticket to tackle it later.
#### Slots
  - [ ] `name` - description
  - [ ] `name` - description
#### Stories
  - [ ] `default` - shows the components default state
  - [ ] `slots` - shows the components slots
  - [ ] `parts` - shows the components parts
  - [ ] `name` - description
#### Samples
  - [ ] `name` - description
  - [ ] `name` - description

### Open Questions towards design
- [ ] Question1
- [ ] Question2

## Subtasks
- [ ] Design_implementation_task
- [ ] Development_implementation_task
- [ ] Design_release_task

## DoR
- [ ] Item has business value
- [ ] All subtasks have been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] All subtasks have been closed
