### ISSUE TITLE
feat: ✨ refactor storybook infrastructure

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#1139]
## User Story

As a maintainer of the Solid Design System I want to improve the infrastructure to be scalable for the future and get rid of past quickwins.

## Subtasks
- [x] #1131 
- [x] #1137
- [x] #1138 
- [x] https://github.com/solid-design-system/internal/issues/60
- [x] https://github.com/solid-design-system/solid/issues/1136

## DoR
- [x] Item has business value
- [x] All subtasks have been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] All subtasks have been closed

**Comment by karlbaumhauer** [comment]
@mariohamann I added this as epic issue for the whole refactoring of storybook. pls have a look into your ticket #1131 if we can extract something into another or new subtask.
