### ISSUE TITLE
feat: ✨ optimize documentation in Figma/Storybook

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#1143]
## User Story
As a User of the Solid Design System, I would like to get a good overview about features of components and styles and more real life example so that I can integrate them easier into my project.

## Subtasks
- [x] #1141

**blocked by #1141**  
- [x] #1142 
- [x] #675 
- [x] #1111 

## DoR
- [x] Item has business value
- [x] Item all subtasks have been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] All subtasks have been closed
