### ISSUE TITLE
docs: 📚 Add documentation to all discontinued ui-components from CL

### ISSUE THREAD

**Issue by yoezlem** [solid-design-system/solid#1155]
## User Story
As a user of the Solid Design System, I would like to have documentation for all discontinued UI components from the Component Library, as well as ensure that all most likely discontinued UI components are properly categorized under "Discontinued UI Components from Component Library", so that I can easily reference which components are no longer in use and why, and maintain a clean and updated Component Library.

### Suggested Solution
- [x] Remove "Most likely discontinued ui-components" and take all components to **"Discontinued ui-components from CL"**
- [x] Add for all discontinued ui-components an one liner why they are no longer in use
<img width="1015" alt="image" src="https://github.com/solid-design-system/solid/assets/98025014/fabb2cd6-043e-495b-a1bd-21b3e0bf0959">

## Subtasks
- [ ] [Design_implementation_task](https://github.com/solid-design-system/solid/issues/551)

## DoR
- [x] Item has business value
- [x] Item all subtasks have been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] All subtasks have been closed
