### ISSUE TITLE
feat: create template for sd-button-group

### ISSUE THREAD

**Issue by coraliefeil** [solid-design-system/solid#1158]
## Problem

In Figma we have a sd-button-group, in code we don’t have that. -> Delta

We’ve learned a lot along the way. And since this group comp is one of the earlier comps and we implemented things like that as samples later on, I think it is time to do some refactoring here.

## Suggestion

After discussion we aligned on renaming the sd-button-group to button-goup-tmpl and move it to the template section.

Since sd-button-group is used/nested in sd-dialog and forms samples we need to update & publish these as well.

- [x] In code we need to add the template accordingly.

## Subtasks
- [x] #1373
- [x] #1374

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Implementation works successfully on `feature` branch
- [ ] updates are published and communicated

**Comment by yoezlem** [comment]
Lets deprecate the sd-button-group and add a sample instead.

@van-nguyen-ht, could you check with @MartaPintoTeixeira for clarity if we are using the sd-button-group somewhere else?

**Comment by van-nguyen-ht** [comment]
@yoezlem @MartaPintoTeixeira In the Solid library, the sd-button-group is only used in sd-dialog and forms samples. CMS library probably more. 

-> To avoid breaking changes for Figma users I recommend renaming rather than deprecate and add another samples. They're built from slots anyways.

**Comment by yoezlem** [comment]
We will add sd-button-group as a template
