### ISSUE TITLE
fix[dev]: 🤔 correct colors in form field validation

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#1172]
## Description
This tasks describes the Figma implementation for: solid-design-system/internal#78 
Chapter 9.1.4.3 in the file "Test Details"

### Task

- [x] For all form fields that have a hover effect of background neutral-200 -> change text color to text.black for the text inside the field. No more green (valid) or red (invalid) text inside form fields.

![Image](https://github.com/user-attachments/assets/290c91ce-7ccc-421d-9ab5-2b0a0f23b026)

- [x] sd-input
- [ ] sd-input - sample autocomplete
- [x] sd-textarea
- [ ] sd-select

### Open Questions towards design
- [ ] Question1
- [ ] Question2

## DoR
- [ ] Item has been estimated by the team
- [ ] Item dependencies have been identified and documented

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch
