### ISSUE TITLE
fix: 🤔 A11y issues - Vorsorgelückenrechner

### ISSUE THREAD

**Issue by coraliefeil** [solid-design-system/solid#1176]
## Todos 

9.1.1.1a Alternative texts for operating elements (Part 1) 

- [ ] [sd-step-group](https://solid-design-system.fe.union-investment.de/x.x.x/storybook/?path=/docs/components-sd-step-group--docs) -> Add the aria label for completed steps, e.g. "To step x - Completed"
- [ ] Check all comps for baked in icons: if they need an aria label

9.1.1.1a Alternative texts for operating elements (Part 2) 

- [x] [sd-input/sample-currency-stepper](https://solid-design-system.fe.union-investment.de/x.x.x/storybook/?path=/story/components-sd-input--samples): Buttons must not be selectable by tab, but arrow up / down

9.1.1.1a Alternative texts for operating elements (Part 3) 

- [x] [sd-tooltip](https://solid-design-system.fe.union-investment.de/x.x.x/storybook/?path=/docs/components-sd-tooltip--docs): Add aria label "info"

9.1.3.1h Labeling of form elements can be determined programmatically 

- [x] [sd-radio-group/radio-butttons](https://solid-design-system.fe.union-investment.de/x.x.x/storybook/?path=/story/components-sd-radio-group--radio-buttons): Check: The group must be enclosed in a <fieldset> element. 

9.1.3.2 Meaningful sequence (Part 1)

- [x] [sd-step-group](https://solid-design-system.fe.union-investment.de/x.x.x/storybook/?path=/docs/components-sd-step-group--docs): the line has to be invisible for screenreaders. the line is not hr, but border

9.1.4.3 Contrasts of texts sufficient (Part 1)

- [x] [sd-step-group](https://solid-design-system.fe.union-investment.de/x.x.x/storybook/?path=/docs/components-sd-step-group--docs): steps in the future ("waiting") need text.secondary color to comply with Level AA. 

- [x] DESIGN feat: ✨ adjust state for step
[#1162](https://github.com/solid-design-system/solid/issues/1162)

9.1.4.3 Contrasts of texts sufficient (Part 2) 

- [x] For all form fields that have a hover effect of background neutral-200 -> change text color to text.black for the text inside the field. No more green (valid) or red (invalid) text inside form fields.
- [x] DESIGN fix: [design] 🤔 color contrast for successfully validated form fields when hovered
[#1165](https://github.com/solid-design-system/solid/issues/1165) 

9.2.4.3 Conclusive sequence for keyboard operation 

- [x] Check tab focus order for sd-input if a tooltip is added to the label slot.

9.3.3.1 Error detection 

- [x] sd-input type numbers / invalid - Recommendation: The form elements must be linked to the error texts using aria-describedby attributes. -> Check

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by yoezlem** [comment]
@coraliefeil I checked all your tasks and add the missing ones as a new task inside here: 
https://github.com/solid-design-system/solid/issues/1166

So I would suggest, we close this one and working with the #1166 Epic.
