### ISSUE TITLE
feat[dev]: ✨ new text color for sd-step-group "waiting" to comply with Level AA

### ISSUE THREAD

**Issue by yoezlem** [solid-design-system/solid#1178]
## Description
This tasks describes the Figma implementation for: #1176 1166
9.1.4.3 Contrasts of texts sufficient (Part 1)

## Task
- [ ] https://solid-design-system.fe.union-investment.de/x.x.x/storybook/?path=/docs/components-sd-step-group--docs: steps in the future ("waiting") need text.secondary color to comply with Level AA.

## DoR
- [ ] Item has been estimated by the team
- [ ] Item dependencies have been identified and documented

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by yoezlem** [comment]
@coraliefeil @MartaPintoTeixeira do we need to tackle here something or can I close it?
