### ISSUE TITLE
feat[dev]: ✨ add aria label to sd-tooltip

### ISSUE THREAD

**Issue by yoezlem** [solid-design-system/solid#1179]
## Description
This tasks describes the Figma implementation for: #1176 
9.1.1.1a Alternative texts for operating elements (Part 3)

### Task
- [ ] [sd-tooltip](https://solid-design-system.fe.union-investment.de/x.x.x/storybook/?path=/docs/components-sd-tooltip--docs): Add aria label "info"

## DoR
- [ ] Item has been estimated by the team
- [ ] Item dependencies have been identified and documented

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by smfonseca** [comment]
The tooltip already has aria-label but it's "tooltip", not "info" has described in the requirements.
