### ISSUE TITLE
feat [design]: ✨ add icon slot to sd-accordion

### ISSUE THREAD

**Issue by mariohamann** [solid-design-system/solid#1195]
## User Story
As a user of the Solid Design System, I would like to have a dedicated slot to place icons inside a `sd-accordion`.

### Suggested Solution
![CleanShot 2024-07-08 at 11 38 56@2x](https://github.com/solid-design-system/solid/assets/26542182/c76ae96e-1cc4-4630-9521-8af2ab4aa9bc)

Ideally the icon appears here, but of course vertically centered. This could help us especially in https://github.com/solid-design-system/solid/pull/1188

## DoR
- [x] Item has business value
- [x] Item have been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Brand approval (---> pending)
- [ ] Figma documentation file incl. hand-off has been created/updated (if applicable)
- [ ] Tokens have been applied/updated (if applicable)
- [ ] Crosslinks are created/updated
- [ ] Implementation works successfully on `figma` branch
- [ ] Published in Figma and communicated in release notes
- [ ] Issues for dependencies have been created (if neccessary)

**Comment by mariohamann** [comment]
@MartaPintoTeixeira Would you mind making a little PoC in a separate branch for sd-accordion?

We would need a boolean property which enables a slot which contains an icon.

**Comment by yoezlem** [comment]
@mariohamann @karlbaumhauer We only needed this feature to find a smooth solution for sd-quickfact, right? Since we now have a solution for that, do we still need this feature in sd-accordion? Otherwise, I would like to close the ticket.

**Comment by mariohamann** [comment]
@coraliefeil Maybe you can have a look but we close it for the moment. :)

**Comment by coraliefeil** [comment]
Since nobody requested an icon in the accordion I will archive the branch. If needed in the future we could easily pick up the POC.
