### ISSUE TITLE
feat: ✨ Create Article for Union Investment Career Page

### ISSUE THREAD

**Issue by yoezlem** [solid-design-system/solid#1224]
## User Story
As a user of the Solid Design System, I would like to create a compelling article for the Union Investment career page, as well as ensure it fits perfectly into a teaser box with a title, text, and image, so that we can attract potential candidates effectively, and enhance our brand presence.

## Additional Information
Webseite: https://unternehmen.union-investment.de/karriere/ihr-karrierelevel/it-karriere

## Subtasks
- [ ] Design_implementation_task
- [ ] Development_implementation_task
- [ ] Design_release_task

## DoR
- [x] Item has business value
- [ ] Item all subtasks have been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] All subtasks have been closed
