### ISSUE TITLE
feat: ✨ typeahead / search in sd-select with multiselect

### ISSUE THREAD

**Issue by tetsuo-repo** [solid-design-system/solid#1271]
## User Story
As a user of the Solid Design System, I would like to be able to select multiple items from sd-select by typing parts of the item label and selecting one or multiple items, so that I don't have to scroll through long lists and pick single items.

Current implementation showing the task.

![sd-select-without-search](https://github.com/user-attachments/assets/2726a5c0-964d-47d1-a5e9-128dcdfa1283)

### Suggested Solution
Combination of sd-select with autocomplete pattern.

## Subtasks
- [ ] Design_implementation_task
- [ ] Development_implementation_task
- [ ] Design_release_task

## DoR
- [x] Item has business value
- [ ] Item all subtasks have been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] All subtasks have been closed

**Comment by coraliefeil** [comment]
These features will be fully covered by the sd-combobox, right? @mariohamann

**Comment by mariohamann** [comment]
Yes

**Comment by coraliefeil** [comment]
@yoezlem this issue can be closed as it duplicates feat: sd-combobox #548

**Comment by coraliefeil** [comment]
I’m closing this issues. It duplicates feat: sd-combobox https://github.com/solid-design-system/solid/issues/548
