### ISSUE TITLE
feat: checkbox group is missing the required attribute (research + implementation)

### ISSUE THREAD

**Issue by smfonseca** [solid-design-system/solid#1275]
## Current behavior
Currently there is no way to mark a checkbox group as required. This behaviour already exists in other components (see sd-radio-group).

## Expected behavior
A `required` attribute exists and allows to check if a child checkbox is checked

## Tasks
- [ ] research
- [ ] implementation

## Technical Information
check: 
- [ ] https://primer.style/components/checkbox-group
- [ ] https://www.lightningdesignsystem.com/components/checkbox/#site-main-content

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by yoezlem** [comment]
Lets talk about this fix. We're not sure what the expetected behavior is (UX wise).

FYI @coraliefeil @MartaPintoTeixeira

**Comment by coraliefeil** [comment]
[See Figma](https://www.figma.com/design/YDktJcseQIIQbsuCpoKS4V/Component-Docs?node-id=2216-41626&node-type=frame&t=scjDVpJqmUqVQbjm-11)

Expected Behavior for a Required Checkbox Group

1. Initial State
Default State: All checkboxes are unchecked.
Required Indicator: A visual indicator (e.g., an asterisk *) is displayed next to the group label to denote that selection is required.

2. Selection Behavior
Single Selection: Users can select one or more checkboxes within the group.
Minimum Selection Requirement: At least one checkbox must be selected for the form to be valid.
Error State: If the user attempts to submit the form without selecting any checkboxes, an error message should be displayed (e.g., “Please select at least one option.”) and the checkbox group should be highlighted.

**Comment by auroraVasconcelos** [comment]
Different Design Systems present the Checkbox Group Required by providing tools for visual indicators, such as a label with * and an invalid state with an error message. However, since each checkbox should be an independent element and selecting one should not affect the others, validation is not commonly implemented directly within the component, leaving it up to the developer to handle it. Additionally, some Design Systems offer the option to add a specific class to provide additional visual support.

During the team meeting, considering the effort required to implement a required variant and the fact that users have not requested this functionality, it was decided not to implement the required variant. Instead, a template will be created, including a JavaScript example demonstrating how to handle validation.
