### ISSUE TITLE
feat: ✨add sd-leadtext to sd-prose

### ISSUE THREAD

**Issue by christophsaile** [solid-design-system/solid#1304]
## User Story
As a User of the Solid Design System, I would like to have the option to use the sd-leadtext inside the sd-prose, so that I can fulify the requested design.

### Suggested Solution
when the sd-leadtext class is used on a element inside the sd-prose, the leadtext should still be styled as a sd-leadtext.

Leadtexts are supported by the tailwind typography component as well:
https://github.com/tailwindlabs/tailwindcss-typography

CMS Figma Link:
https://www.figma.com/design/QjYmW5zZuGLdnSibmDD2Fo/UI-CMS-Library?node-id=2871-6621&t=beKLVDtiqUdFnGrt-0

<img width="542" alt="image" src="https://github.com/user-attachments/assets/953553ef-a098-474b-bc91-575b81150ebb">

### Current Behaviour
inverted state is not working + the font-size is not correct:

![image](https://github.com/user-attachments/assets/3957f20f-ab1a-4ace-a785-7a1eca8b4c6a)

## Subtasks
- [x] Design_implementation_task
- [ ] Development_implementation_task
- [ ] Design_release_task

## DoR
- [ ] Item has business value
- [ ] Item all subtasks have been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] All subtasks have been closed

**Comment by christophsaile** [comment]
Hey @coraliefeil, can you please have a look at this issue? I am currently working on a ticket that requires the usage of the sd-leadtext inside the sd-prose. I already talked with @mariohamann, and he agreed that this feature is valuable. Furthermore, we already found a technical solution for this requirement.
Can you adjust the sd-prose design file and include the leadtext option, or do you see anything that speaks against this feature?

**Comment by coraliefeil** [comment]
Yes, we can adjust sd-prose accordingly @christophsaile

**Comment by coraliefeil** [comment]
> Yes, we can adjust sd-prose accordingly [@christophsaile](https://github.com/christophsaile)

[Sample done](https://www.figma.com/design/VTztxQ5pWG7ARg8hCX6PfR/Solid-DS-%E2%80%93-Component-Library?node-id=28148-1441&t=W0mEHPcMrhv8NwCe-11)

[Docs done](https://www.figma.com/design/2PTbB1Tqx2COE53bEgEGsO/Prose?node-id=2201-2191&t=uxi536t8syt4RVP2-11)
