### ISSUE TITLE
feat: ✨ BREAKING CHANGES

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#1375]
## User Story
Epic issue to collect all breaking changes.

All subtasks should be merged at once (maybe even together with the rewrite docs PR).

## Subtasks
- [x] #1296 
- [x] #1339 
- [x] #1310 
- [x] #1314
- [x] #1418

## DoR
- [x] Item has business value
- [ ] Item all subtasks have been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] All subtasks have been closed
