### ISSUE TITLE
feat: ✨ A11y Audit improvements

### ISSUE THREAD

**Issue by yoezlem** [solid-design-system/solid#1465]
## User Story
As a user of the Solid Design System, I would like to ensure all components are fully accessible, as well as verify that they adhere to WCAG 2.2 standards, so that I can use the system efficiently regardless of any accessibility needs, and ensure a consistent, inclusive experience across all applications.

### Components
- [x] #1466
- [x] #1468 
- [x] #1469
- [x] #1470
- [x] #1471
- [x] #1472
- [x] #1473 
- [x] #1474 
- [x] #1475 
- [x] #1476 
- [x] #1477 
- [x] #1478 
- [x] #1479 
- [x] #1480 
- [x] #1481
- [x] #1482
- [x] #1483 
- [x] #1484 
- [x] #1485 
- [x] #1486 
- [x] #1487
- [x] #1488 
- [x] #1489 
- [x] #1490 
- [x] #1491
- [x] #1492
- [x] #1493
- [x] #1494
- [x] #1495 
- [x] #1496 
- [x] #1497 
- [x] #1498
- [x] #1499
- [x] #1500 
- [x] #1501
- [x] #1502 
- [x] #1503
- [x] #1504 
- [x] #1505 
- [x] #1506 
- [x] #1507
- [x] #1612
- [x] #1613

### Templates
- [x] #1508 
- [x] #1509
- [x] #1510
- [x] #1511 
- [x] #1512 
- [x] #1513 
- [x] #1515 
- [x] #1516 
- [x] #1517 
- [x] #1518 
- [x] #1519 
- [x] #1520
- [x] #1521 
- [x] #1522
- [x] #1523
- [x] #1524 
- [x] #1525 
- [x] #1526
- [x] #1527
- [x] #1528 
- [x] #1529
- [x] #1530
- [x] #1531
- [x] #1532 
- [x] #1533
- [x] #1534

## DoR
- [x] Item has business value
- [x] Item all subtasks have been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] All subtasks have been closed
