### ISSUE TITLE
feat: ✨ new sd-flipcard concept

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#1540]
## User Story
As a user of the Solid Design System, I would like to utilize an interactive `sd-flipcard` where all known a11y issues are tackled, so that I can rely on an a11y-tested and -approved library.

### Suggested Solution
Rework the `sd-flipcard` to mach WCAG2.2 criteria, especially when being interactive.
-> This means we have to remove the activation property, default is always the click.
1. Refactor component from UX perspective => take #1541 into account
2. Adopt code component

## Subtasks
- [x] #1543 
- [x] #1314 
- [x] #1544 
- [x] #1175
- [x] #1591

## DoR
- [x] Item has business value
- [x] Item all subtasks have been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] All subtasks have been closed

**Comment by yoezlem** [comment]
On hold until we know how to handle non-accessible components that require much more work to make them accessible.

FYI. @coraliefeil @karlbaumhauer

**Comment by coraliefeil** [comment]
Flipcard with bottom alignment for all variants and flip button to ensure A11y is published from design side.

Further tasks are only dev related.

**Comment by mariohamann** [comment]
Done.
