### ISSUE TITLE
feat: ✨ refactor build in components

### ISSUE THREAD

**Issue by mariohamann** [solid-design-system/solid#1571]
(This is a spin off of https://github.com/solid-design-system/solid/issues/1131)

## User Story
As a maintainer of the Solid Design System, I would like to have a more scalable and robust infrastructure, so that we're prepared for upcoming features and to better understand how parts of the design system interact with each other.

### Suggested Solution

1. The build scripts in `/components` focus only the build step, similar to what [Shoelace (build.js)](https://github.com/shoelace-style/shoelace/blob/next/scripts/build.js) and [Synergy (build.js)](https://github.com/synergy-design-system/synergy-design-system/blob/main/packages/components/scripts/build.js) does. Our `cdn` and `package` separation should be refactored as written below. Furthermore this should be fixed during that: https://github.com/solid-design-system/solid/issues/859#issuecomment-2017457770
2. Tests use these build scripts instead of the current Vite setup. I expect that this will solve #1112 as well.

## Technical Information

There will be tough nuts to crack, like importing `styles` into `components` including live updates, rewriting the build scripts etc.
The biggest challenge will be to make the vite magic (being used in Storybook) fully compatible with `esbuild` and making the tests work at the same time.

One important part will be improving and fixing the builds. This might become a really big change. Currently the final build looks like the following:

```
dist/
     components/
                es/
                   solid-components.js
                   solid-components2.js (containing utilities)
                   input.js
                   umd/solid-components.js
       package/
               components/
                          solid-components.js
                          utilities/
                                    autocomplete-config.js
                          components/
                                     input.js
       versioned-components/
                  es/
                     solid-components.js
                     solid-components2.js (containing utilities)
                     input.js
                  umd/solid-components.js
```

There are big problems coming with the current builds, e. g. that you can't select `utilties` in an appropriate file from the `components` folder.

I think we should aim for the following, whcih works well for Shoelace:

```
dist/
       solid-components.js
       solid-components.iiff.js (containing the whole bundle!)
                utilities/
                          autocomplete-config.js
                          autocomplete-config.min.js
                          components/
                                     input.js
                                     input.min.js
versioned-dist/
                         ...
cdn/
       (everything minified including bundled lit etc)
       solid-components.js (containing the whole bundle!)
       solid-components.iiff.js (containing the whole bundle!)
                utilities/
                          autocomplete-config.js
                          autocomplete-config.min.js
                          components/
                                     input.js
                                     input.min.js
versioned-cdn/
                         ...
```

## Subtasks
- [x] Make tests running without any fails @paulovareiro29 – checkout how Synergy and Shoelace did it, including some more specific tests like the one for the `sd-icon` 
- [x] extract regex transformation from `esbuild-plugin-lit-tailwind.js` into own function that is exported; move `vite-plugin-lit-tailwind.ts` into `packages/docs` and exchange the transformation with the exported function from `esbuild-plugin-lit-tailwind` @paulovareiro29 
- [x] harmonize import of global styles following Lit's proposal and get rid of component.styles and multiple imports @mariohamann 
- [x] Setup Meta data
- [x] Setup versioning for components
- [x] Setup versioning for meta data (append data vs. new file?)
- [x] Setup versioning for styles
- [x] make styles structure flat,, only single modules, prose and index
- [x] make styles work with Storybook
- [x] Export and publish `_utilties.css`, as it has to be imported in the very end
- [x] Make linters etc. work again
- [ ] Update docs and make section about breaking changes (?)
- [ ] Update installation guides
- [ ] Setup Releases for Styles package
- [x] re-add cssnano

## DoR
- [ ] Item has business value
- [ ] Item all subtasks have been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] All subtasks have been closed

**Comment by mariohamann** [comment]
To fulfil #859 and #1112 I'm working on this ticket. This will handle #1570 as well. @paulovareiro29 is supporting me. I will use the initial ticket, to keep track of things have to be done.
