### ISSUE TITLE
feat: sd-badge variant names a11y update 

### ISSUE THREAD

**Issue by smfonseca** [solid-design-system/solid#1593]
## User Story
Problem: In the docs, it says that the success and error variants don't imply any semantic meaning. They kinda do because they tell me that something good, bad, or neutral is going on. You can argue that the number itself is enough to communicate that information, at least as a fallback, but that's not the case in the sm variation. It only communicates the state visually.

Solution:
- [x] Extend the hint to make clear why we have the variant names
- [x] Change variants names  to `blue`, `red` and `green` to avoid connotations
- [ ] Implement changes in code
- [ ] add migration guide to the `v3` section

Discussion regarding this change can be found [here](https://github.com/solid-design-system/solid/pull/1563#issuecomment-2432242006).

## DoR
- [ ] Item has business value
- [ ] Item all subtasks have been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] All subtasks have been closed

**Comment by coraliefeil** [comment]
Done from design side.
[Figma Comp](https://www.figma.com/design/VTztxQ5pWG7ARg8hCX6PfR/Solid-DS-%E2%80%93-Component-Library?node-id=4687-24978&node-type=frame&t=Q3W7tGecQb6vxaLm-11)
[Figma Docs](https://www.figma.com/design/YDktJcseQIIQbsuCpoKS4V/Component-Docs?node-id=2093-6934&node-type=canvas&t=xwmsVFsfgZDgkimt-11)

Ready for code update.
