### ISSUE TITLE
feat[design]: ✨ update sd-menu docs

### ISSUE THREAD

**Issue by coraliefeil** [solid-design-system/solid#1718]
## Description
This tasks describes the Figma implementation for: #594 

### Task

[Menu branch](https://www.figma.com/design/FXKazpLW1CbwevqkcgfUMx/sd-menu-V.0.0.1?node-id=15003-4416) needs to be updated in order to meet our latest docs rewrite.

Needs to be in a good shape when dev can pick up this tasks.

### Open Questions towards development
- [ ] Question1
- [ ] Question2

## DoR
- [ ] Item has been estimated by the team
- [ ] Item dependencies have been identified and documented

## DoD
- [ ] Brand approval (if neccessary)
- [ ] Figma documentation file incl. hand-off has been created/updated (if applicable)
- [ ] Tokens have been applied/updated (if applicable)
- [ ] Crosslinks are created/updated
- [ ] Implementation works successfully on `figma` branch

**Comment by coraliefeil** [comment]
Pls assign me if my review is needed here.

**Comment by coraliefeil** [comment]
Great thx. We’ll continue there as soon as code implementation starts.
