### ISSUE TITLE
feat: ✨ setup eslint custom rules package

### ISSUE THREAD

**Issue by paulovareiro29** [solid-design-system/solid#1735]
## User Story
As an external developer using the Solid Design System, I would like to make my code more robust using code best practices, by following eslint rules.

### Suggested Solution
An Eslint Custom Rules package is setup on the monorepo to provide guidance to external developers using the SDS.

## Subtasks
- [ ] Setup eslint custom rules package
- [ ] Structure package to handle custom eslint rules, in a nice way.
- [ ] Investigate if the new package can be set as a peer dependency of the components package, to avoid versions mismatch between components and eslint rules on external developers projects.

## DoR
- [x] Item has business value
- [x] Item all subtasks have been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] All subtasks have been closed

**Comment by yoezlem** [comment]
@paulovareiro29 please add SP for this feature.

**Comment by coraliefeil** [comment]
Moved to future iteration ...
