### ISSUE TITLE
🙌  Epic: Navigation

### ISSUE THREAD

**Issue by mariohamann** [solid-design-system/solid#241]
There are several issues, that have to be resolved to create navigations with SDS:

- [x] solid-design-system/solid#232 
- [x] solid-design-system/solid#228 
- [x] solid-design-system/figma#107
- [x] #346
- [x] solid-design-system/solid#301 
- [ ] sd-header: solid-design-system/design#72 
- [ ] sd-navigation-item: solid-design-system/design#58 
- [x] sd-navigation: solid-design-system/design#28
- [ ] sd-drawer (design): solid-design-system/design#54 
- [x] solid-design-system/solid#314
- [x] solid-design-system/solid#316 
- [x] solid-design-system/solid#315 
- [x] #353
