### ISSUE TITLE
🙌 Epic: End of Friendly User Phase

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#259]
To provide the above mentioned epic as a new feature to the SDS, the following tasks are already created and need to be closed:
- [x] solid-design-system/solid#250
- [x] solid-design-system/solid#207
- [x] solid-design-system/solid#206
- [x] solid-design-system/solid#175
- [x] solid-design-system/solid#60
- [ ] solid-design-system/solid#249

In addition to this, a new issue need to created and added into the list above for the following topics:
- [ ] tbd
