### ISSUE TITLE
🙌 Epic: Typography

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#260]
To provide the above mentioned epic as a new feature to the SDS, the following tasks are already created and need to be closed:
- [x] solid-design-system/solid#133
- [x] #263
- [x] #264
- [x] #266
- [x] #265 
- [ ] #267 (needs to be discussed)
- [ ] #317 (needs to be discussed)
- [ ] solid-design-system/solid#243  (needs to be discussed)

**Comment by yoezlem** [comment]
@coraliefeil paragraph, display, leadtext and quote will be the first "styles" which will be finished.
sd-mark needs to be created by you (design). It make sense to use this exactly like the other styles -> sd-mark (marks the green color in text) so we can add it to all components as class. 

we can than clearify footnote, headline and meta afterwards :)

Is this okay for you?
