### ISSUE TITLE
Prepare Tailwind classes for forms milestone

### ISSUE THREAD

**Issue by mariohamann** [solid-design-system/solid#261]
I would like to prepare our form milestone as good as possible, so that we can focus on logic and functionality instead of styling.

Therefore I would propose that we already start working on the conversion of Shoelace style to Tailwind classes and maybe even preparing some stories:

Let's do it all in this branch: https://github.com/solid-design-system/solid/tree/feat/add-form-elements

Regarding how to convert SCSS to TailwindCSS see e. g. https://github.com/solid-design-system/solid/branches/active

- [ ] `sd-textarea`
  - [ ] move from `_components` into `components`
  - [ ] convert from SCSS to TailwindCSS [HandOff](https://www.figma.com/file/07Bzd23A0QSrSWiXy6w2uM/Text-Area?type=design&node-id=6-4&mode=design&t=rIXHhHmZPdC9d3px-11) 
  - [ ] create stories (sizes, states, ...)
- [ ] `sd-checkbox`
  - [ ] move from `_components` into `components`
  - [ ] convert from SCSS to TailwindCSS: [HandOff](https://www.figma.com/file/Q7E9GTBET7Gs2HyH1kbpu5/Checkbox-%2F-Checkbox-Group?type=design&node-id=0-1&mode=design&t=iNUQ7yFZQ5FEIWbg-11)
  - [ ] create stories (sizes, states, ...)
- [ ] `sd-select`
  - [ ] move from `_components` into `components`
  - [ ] convert from SCSS to TailwindCSS [Handoff](https://www.figma.com/file/ZphyVFsUHL72voMrJagMeo/Select?type=design&node-id=0-1&mode=design&t=fwAHJ726szQGhZwk-11)
  - [ ] create stories (sizes, states, ...)
- [ ] `sd-input`
  - [ ] move from `_components` into `components`
  - [ ] convert from SCSS to TailwindCSS [Handoff](https://www.figma.com/file/xSIeTnyfW2T21Uw5JgdZOg/Input?type=design&node-id=6-4&mode=design&t=W6hfyyPWvuBT2R8d-11)
  - [ ] create stories (sizes, states, ...)

**Comment by karlbaumhauer** [comment]
@mariohamann do we still need this and if yes, pls prepare for the new forms developers.

**Comment by mariohamann** [comment]
No. :) We have Özlem's branch as base now.
