### ISSUE TITLE
🙌 Epic: Navigation

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#262]
To provide the above mentioned epic as a new feature to the SDS, the following tasks are already created and need to be closed:
- [x] solid-design-system/solid#232
- [x] solid-design-system/figma#107
- [x] solid-design-system/solid#243
- [x] #367 

In addition to this, a new issue need to created and added into the list above for the following topics:
- [ ] tbd
