### ISSUE TITLE
feat: ✨ add autocomplete pattern + helper

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#269]
## User Story

As a developer I want to be able to easily use an input with autosuggest functionality that fits to the Solid Design System.

## Acceptance criteria

- [x] Use the branch https://github.com/solid-design-system/solid/tree/feat/autocomplete as a base and optimize styles regarding to [Figma design](https://www.figma.com/file/VTztxQ5pWG7ARg8hCX6PfR/Solid-DS-%E2%80%93-Component-Library?type=design&node-id=401-2294&mode=design).
- [x] Describe why we decided to offer a helper for an existing library (https://tarekraafat.github.io/autoComplete.js/#/) instead of writing a component (a11y, keyboard handling, flexibility, bundle size etc. etc.)
- [x] helper function `packages/components/src/utilities/setup-autocomplete.ts`
  - [x] make it importable via ESM and usable via UMD
  - [x] describe its functionality, its defaults (injecting popup etc.) and which settings its offers
  - [x] describe its return value `config`
  - [x] describe how to utilize the script and config in combination with autocomplete.js
  - [x] point to the docs of autocomplete.js
- [x] Add additional docs and stories which show how to...
  - [x] describe the existing stories, what they can do and how they work
  - [x] use completely different elements like sd-option with icons or avatars etc. as an list element
  - [x] inject styles into the shadow-dom of `sd-input`
  - [ ] ~set custom height as requested in https://jira.apps.union-investment.de/browse/PB2B-3883~ -> #817 
  - [ ] ~You can set a max number of elements, the element resizes automatically regardign the space on the window and makes its content scrollable.~ -> #819
  - [ ] ~think of other examples, like fetching data async etc. (get inspiration from e. g. download-search or similar)~ -> #980 
- [x] write some tests to test `setup-autocomplete.ts`
- [ ] ~make the initial docs page that it doesn't show the first story and the args table (see e. g. https://github.com/synergy-design-system/synergy-design-system/blob/main/packages/docs/stories/templates/form.stories.tsx#L20) and do the same for `quote`~-> #905 
- [x] Double check that everything works when you use our package or CDN output (using in another project)

## Technical information
>Note: this branch will bring some improved HTML formatting for the source-code-view in storybook.
## Related tickets
- [ ] - ~https://jira.apps.union-investment.de/browse/PB2B-3883~ -> #817 

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by karlbaumhauer** [comment]
@mariohamann @yoezlem 
I close the ticket in Jira where B2B devs requested an external hight setter for this component. To prevent missing this when we start with the autosuggest, I added a hint into the description. Please take this into account by refining the ticket.

**Comment by coraliefeil** [comment]
On hold ... waiting for feedback from shoelace.

**Comment by mariohamann** [comment]
@Vahid1919 Let's have a look on this: https://github.com/algolia/autocomplete

**Comment by karlbaumhauer** [comment]
@Vahid1919 I created #686 for the research in order to track the status. Pls remove yourself from this ticket until we start implementing the feature. This Ticket is not ready to start as the description is nearly empty.

**Comment by saemik94** [comment]
current Figma branch: https://www.figma.com/file/VTztxQ5pWG7ARg8hCX6PfR/branch/7NQdTrhruyGE9ioafYYcdc/Solid-DS-%E2%80%93-Component-Library?type=design&node-id=19938-5032&mode=design&t=BhK5AIzAQqYRVGLW-0#711807364

**Comment by saemik94** [comment]
As discussed with Mario, the customization of the sd-popup is outsourced to a separate ticket #817
