### ISSUE TITLE
feat: ✨ add sd-audio

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#270]
As a stakeholder of the Solid Design System, I want to utilize the new `sd-audio` component to provide audio content in a more appealing and dynamic way, so that end-users can engage with the content more effectively and have a better user experience.

## Documentation & Hand-off
https://www.figma.com/file/cHffrwo9yDeKpqsPcYN8R7/sd-audio-V.1.0.0?type=design&node-id=3112-19985&mode=design

#### Props
| Status | Name | Type | Default | Description |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| <ul><li>[x] </li></ul>  | `inverted` | `boolean` | `false` | inverts the colors for use on primary background |
| <ul><li>[x] </li></ul>  | `reversedLayout` | `boolean` | `false` | positions the controls below the timeline |
| <ul><li>[x] </li></ul>  | `animated` | `boolean` | `false` | activates the wave animation |

#### Parts (besides the shoelace parts)
  - [ ] every other HTML element (depending on the HTML structure) => NOTE: if highlighting the parts in the `parts` story does not work out of the box, do not spend more effort on it but open a bug ticket to tackle it later.
#### Slots
  - [x] `default` - place for the audio player
  - [x] `transscript` - by default hidden slot to provide the transcript (only if the <track> solution doesn't work).
  - [x] `play/pause` - provides a slot to replace play and pause icon/button?!
#### Stories 
  - [x] `default` - displays the default state of the component
  - [x] `slots` - displays all the slots
  - [x] `reversed layout` - displays the component with reversed control order
  - [x] `parts` - all the parts
  - [x] `backgrounds` - shows the player on 3 different backgrounds (as in Figma)

#### Samples
  - [x] `large info` - shows a player with complex content
  - [x] `transcript` - shows a player with added transcript
  - [x] `teaser` - shows the player with a teaser

### Open questions towards development
- [x] Do we need the speed toggle as property to be able to set it programmatically? => nope
- [x] The same with the transscript? => nope

### Open Questions towards design
- [x] [standard HTML player](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_audio) has a "download" feature implemented into the 3-dot-menu (next to speed). Do we use this as well? 
-> IMO we cannot offer a download functionality due to legal / license reasons. Since we did not discuss it earlier and it hasn’t bee requested yet ... I would skip that.  
- [x] transcript - is html embedding sufficient for wcag compliance? yes
- [x] speed toggle or speed dropdown? => toggle
- [x] Accessibility Transcripts are needed: https://www.w3.org/WAI/media/av/captions/
- [x] Similar to the sd-video component, we just provide a wrapper component with the default slot, where the html player element has to be placed.

### Technical Information
- [x] our new SDS-Song should be used => the file is uploaded into our internal teams folder as the file cannot be uploaded here. In case the permission does not work, pls kontakt @karlbaumhauer or @yoezlem to receive the file.
- [x] download feature from HTML audio player needs to be deactivated (if neccessary).
- [x] transcript will be placed into the `transcript` slot, which opens up a `sd-drawer` to display it. ([Example](https://ableplayer.github.io/ableplayer/demos/audio4.html) or on UDEMY) 
- [x] HTML audio player is used as basis for our sd-audio player => especially the controls
- [x] For the track-knob and the volume-knob, the `sd-range` styles need to be exported and reused
- [x] `play / pause` -> primary button with overriden size and radius
- [x] for the playback speed, we favor the idea of toggling through the different options (1x, 1.25x & 1,5x) but if this is too complex in development, we go back to the native dropdown behavior in HTML player.
- [x] the wave animation has already been implemented in the [ui-audio-player](https://component-library.fe.union-investment.de/latest/storybook/index.html?path=/story/components-audio-player--animated)
- [x] aria-labels (mute, play etc.) need to be localized and added to the localize file AND need to be reactive.

## Subtasks
- [x] #1017
- [x] #1164
- [ ] #1018
- [ ] #1019

## DoR
- [x] Item has business value
- [x] All subtasks have been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] All subtasks have been closed

**Comment by yoezlem** [comment]
This component seems to me like something only the CMS teams will use. @EllaELSA & @coraliefeil, can you also take a look here?

**Comment by coraliefeil** [comment]
To do @coraliefeil - collect good references and come up with a solid basic component in design sparring with @EllaELSA

**Comment by coraliefeil** [comment]
Hey @van-nguyen-ht I’ll hand this over to you to bring it into a good shape. Pls keep the research and design proposal section because we want to run all of it also through brand.

I presented it in todays pre-refinement. Team alignment and all infos in the issue description are up to date.

Here’s the [Figma Branch](https://www.figma.com/file/cHffrwo9yDeKpqsPcYN8R7/sd-audio-V.1.0.0?type=design&node-id=3112-19985&mode=design)

Have fun with it <3

**Comment by van-nguyen-ht** [comment]
[Design component](https://www.figma.com/file/VTztxQ5pWG7ARg8hCX6PfR/branch/cHffrwo9yDeKpqsPcYN8R7/Solid-DS-%E2%80%93-Component-Library?type=design&node-id=21798-1702&mode=design&t=LinIx4QWONKIeiIR-11) is ready for review, would you mind having a look? @coraliefeil @mario

Fyi Mario, regarding non-touch device I find any current design component documentation on that, an example I see on [cnn](https://edition.cnn.com/videos) there's no options for speed either.

**Comment by coraliefeil** [comment]
Pls assign Mario and me and move issue to review column. thanks <3

**Comment by coraliefeil** [comment]
@van-nguyen-ht thanks ... I left some comments in the branch

**Comment by van-nguyen-ht** [comment]
Hi @Vahid1919 I left you some comments, here's the references 

<img width="455" alt="Screenshot 2024-04-03 at 13 22 42" src="https://github.com/solid-design-system/solid/assets/118520877/cbf694de-0b33-4d31-be75-a8c4263c6c16">

https://github.com/solid-design-system/solid/assets/118520877/acd82f22-35cb-4748-b585-ee6a8c25f0db

@karlbaumhauer can I leave these here and delete when Vahid is done?

**Comment by van-nguyen-ht** [comment]
@mariohamann Hi Mario, should/how can I add more animation specs? [Reference](https://component-library.dev.fe.union-investment.de/integration/storybook/index.html?path=/story/components-audio-player--animated)

**Comment by van-nguyen-ht** [comment]
[Figma Branch](https://www.figma.com/file/cHffrwo9yDeKpqsPcYN8R7/sd-audio-V.1.0.0?type=design&node-id=3112-19985&mode=design) 

already clarified with Mario:
-no animation documentation needed (Front-end will reuse component)
-no *background-gradient.primary|10 token needs to be recorded

**Comment by mariohamann** [comment]
I have strong concerns regarding the transcripti and we will provide here, but let's see. From a migration perspective, I would propose to focus on the actual audio element and ignore transcripts for now. We don't hinder a11y here, if we don't include this in our component, as transcripts can be easily added anywhere.

Besides that I think we should add several slots to the button area, to allow people to set their own actions if needed.

**Comment by mariohamann** [comment]
@yoezlem I removed myself, you can now take over.

**Comment by karlbaumhauer** [comment]
@coraliefeil, @van-nguyen-ht & @mariohamann I added some small questions in the ticket. maybe you can have a quick look into it and quickly awnswer them until the daily.

**Comment by coraliefeil** [comment]
@karlbaumhauer I’ve answered all design questions

**Comment by coraliefeil** [comment]
@smfonseca we added the inverted feature FYI

**Comment by coraliefeil** [comment]
Renamed boolean: wave-animation -> animated

**Comment by karlbaumhauer** [comment]
as discussed with dev and design, the audio slider has been removed => https://github.com/solid-design-system/solid/pull/1194#discussion_r1777376321
