### ISSUE TITLE
🙌 Epic: Text-Image-Video

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#282]
To provide the above mentioned epic as a new feature to the SDS, the following tasks are already created and need to be closed:
- [ ] solid-design-system/solid#281
- [ ] solid-design-system/solid#276
- [ ] solid-design-system/solid#278
- [ ] sd-image docs: solid-design-system/figma#17

In addition to this, a new issue need to created and added into the list above for the following topics:
- [ ] tbd
