### ISSUE TITLE
feat: ✨ add sd-flipcard

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#299]
## User Story
As a user of the Solid Design System, I want to utilize a Flashcard component with flip animation to add dynamic and interactive content to pages, providing a visually engaging way to present and interact with information.

## Documentation
https://www.figma.com/file/JZZL5QPXQVKVGt4CHBlNlz/Flashcard?type=design&node-id=1301-7360&mode=design&t=eaEgzwqpgma861CK-0

## Hand-off
https://www.figma.com/file/JZZL5QPXQVKVGt4CHBlNlz/Flashcard?type=design&node-id=6-4&mode=design&t=eaEgzwqpgma861CK-0

#### Props
| Status | Name | Type | Default | Description |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| <ul><li>[ ] </li></ul>  | `frontVariant` | `primary` / `primary-100` / `gradient light-top` / `gradient light-bottom` / `gradient dark-top` / `gradient dark-bottom`| `primary` | The sd-flashcards theme variant |
| <ul><li>[ ] </li></ul>  | `backVariant` | `primary` / `primary-100` / `gradient light-top` / `gradient light-bottom` / `gradient dark-top` / `gradient dark-bottom`| `primary` | The sd-flashcards theme variant |
| <ul><li>[ ] </li></ul>  | `ratio` | `3:4` / `16:9` | `3:4` | the ratio for the layout of the flashcard |

#### CSS-Properties
  - [x] `name` - description
#### Parts (besides the shoelace parts)
  - [x] every other HTML element (depending on the HTML structure) => NOTE: if highlighting the parts in the `parts` story does not work out of the box, do not spend more effort on it but open a bug ticket to tackle it later.
#### Slots
  - [x] `front` - for the content on the front side of the flashcard
  - [ ] `back` - for the content of the back side of the flashcard
  - [ ] `mediaFront` - An optional media slot which can be as a background. Dependent from gradient variant.
  - [ ] `mediaBack` - An optional media slot which can be as a background. Dependent from gradient variant.
#### Stories (besides the `default` story)
  - [ ] `Variant` - (description)
  - [ ] `Ratio` - (description)
#### Samples
  - [ ] `Clickable Flashcard` - Only it is necessary that is allowed to do it semantically (accessible way).

 #### Methods
| Status | Name | Description |
| ------------- | ------------- | ------------- |
| <ul><li>[ ] </li></ul>  | `flip-front` | Shows the content of the quickfact. |
| <ul><li>[ ] </li></ul>  | `flip-back` | Hides the content of the quickfact. |

 #### Events
| Status | Name | Description |
| ------------- | ------------- | ------------- |
| <ul><li>[ ] </li></ul>  | `sd-flip-front` | Shows the content of the quickfact. |
| <ul><li>[ ] </li></ul>  | `sd-flip-back` | Hides the content of the quickfact. |

### Open Questions towards design
- [ ] Question1
- [ ] Question2

### Technical Information
- [ ] transition from back/flip is 1000ms
- [ ] We have to check if its allowed to add a link inside a button (accessiblity perspective). Generally we have to check nested elements. Please document that. 
- [ ] we have to make sure that both sides are searchable and available in the DOM. Maybe we can use the `summary` and `details` from accordion.

## Subtasks
- [x] #1011
- [x] #1012
- [x] #1013

## DoR
- [x] Item has business value
- [x] All subtasks have been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] All subtasks have been closed

**Comment by mariohamann** [comment]
The current `sd-flashcard` component duplicates much of the logic of our upcoming `media-teaser`.

I would strongly recommend to: 
- a.) make this thing just an element with two slots for frontside and backside, reducing it's logic to only "turning itself". Examples for that are e. g.  https://github.com/jeffreyquan/flip-card-wc / https://codepen.io/jeffreyquan/pen/ZEByKRL or maybe https://www.webcomponents.org/element/@adaws/flip-card – in Figma we then inform that this component consists of two sides and we show all current implementations as examples.
- b.) Drop this thing completely and just let CMS do their stuff – @EllaELSA hat concerns regarding this component in general. I have some concerns regarding its UX as well (how do users know, that this thing is clickable/hoverable if there is no trigger?)

I therefore set this to triage.

**Comment by coraliefeil** [comment]
Could we find out how often it is being used? @karlbaumhauer

**Comment by karlbaumhauer** [comment]
I asked the BE to send me an usage report. Lets see what they can provide.

**Comment by karlbaumhauer** [comment]
> Could we find out how often it is being used? [@karlbaumhauer](https://github.com/karlbaumhauer)

@coraliefeil do you still need to know some pages where it is used? I received the export from backend.

**Comment by coraliefeil** [comment]
@karlbaumhauer sure ... always good to gain insights <3 Thank you!

**Comment by coraliefeil** [comment]
@van-nguyen-ht sd-flashcard needs to be refactored
e.g. gradient versions should be rebuilt according to sd-teaser-media ... where the gradient grows according to text content ... so we can make sure it is wcag compliant. 
Other things we need to adjust to update the comp to current standards?

**Comment by van-nguyen-ht** [comment]
@coraliefeil I can't think of anything else we need to adjust. I'll take care of this once the plugin is approved.

**Comment by karlbaumhauer** [comment]
> Since no one remembers why it is called "flashcard" ... I was wondering if we could rename it to "flipcard" which makes the usage instantly clear.
> 
> What do you think? @solid-design-system/core-design @solid-design-system/core-development

according to Copilot, "flipcard" is the most common name for such a component... ;-)

**Comment by van-nguyen-ht** [comment]
flipcard actually describe the function better than flashcard :)
