### ISSUE TITLE
research: Hidden Links

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#3]
- [x] research which kind of buttons we can/should provide and which technical solution would fit the best for us.
- [x] create a respective ticket for design and dev

----

We would like to provide the users of the design system with guidelines to implement the hidden accessibility buttons feature in the best possible way.

Approach 1 [Skip to content] - After the initial page load, a hidden button "Skip to content" is displayed after pressing the tab key. This anchor scrolls to the main content of the page. (Example: https://www.spiegel.de/)

Approach 2 [Quicklinks on Tab] - After initial pageload, a hidden button "Main menu" is displayed after pressing the tab key. If you press the tab key again, a hidden button "Booking form" is displayed, another tab shows "Content", another tab shows "Footer navigation" (example: https://www.motel-one.com/de/)

Approach 3 [Quicklink menu in dropdown] - After initial pageload, a hidden dropdown "Jump to" with a quicklink menu is displayed after pressing the tab key. The arrow keys can be used to focus on "Content, navigation, search, sidebar, footer". (Example: https://uni-freiburg.de/)

Questions:

Approach 1 is the minimum you need to fulfill to be accessible on the site? https://www.w3.org/TR/WCAG20-TECHS/G1.html

If you want to offer more quicklinks ... is approach 2 or 3 better? Or does it simply depend on the purpose/structure of a page? Example Motel One - here it is important to get people quickly to the booking page.

## Subtasks
- [x] #1101
- [x] #1102

## DoR
- [x] Item has business value
- [x] All subtasks have been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [x] All subtasks have been closed

**Comment by coraliefeil** [comment]
@yoezlem I picked up this issue labeled iteration 9 from the backlog since it is pretty small and added 2 points for it. Is this ok for you?

**Comment by yoezlem** [comment]
Go for it. We will create another Ticket after the research for the implementation. So you won't have dependencies, right?

**Comment by coraliefeil** [comment]
Yes, no dependencies ATM.

**Comment by coraliefeil** [comment]
@yoezlem We got feedback from Damaris. I would like to discuss options and what we would like to provide for this topic in the next pre-refinement session.

**Comment by coraliefeil** [comment]
I’ve published the design pattern in [figma](https://www.figma.com/design/VTztxQ5pWG7ARg8hCX6PfR/Solid-DS-%E2%80%93-Component-Library?node-id=25439-3495&t=U6UJAZ8JsNWufBpL-11).
