### ISSUE TITLE
feat: ✨ add sd-expandable

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#300]
## User Story
As a Solid Design System user, I want to use `sd-expandable` to hide and reveal content, providing a more streamlined viewing experience.

## Description
https://www.figma.com/file/owNwnmTLTH7rDD4kOyGJK9/Expandable?type=design&node-id=0-1&mode=design&t=O19pLS2K6qNkdN1M-0

## Hand-off
https://www.figma.com/file/owNwnmTLTH7rDD4kOyGJK9/Expandable?type=design&node-id=6-4&mode=design&t=O19pLS2K6qNkdN1M-0

#### Props
| Status | Name | Type | Default | Description |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| <ul><li>[x] </li></ul>  | `open` | `boolean` | `false` | Used to check whether the component is expanded or not. |
| <ul><li>[x] </li></ul>  | `inverted` | `boolean` | `false` | Inverts the expandable and sets the primary color background.|

#### Parts (besides the shoelace parts)
  - [x] every other HTML element (depending on the HTML structure) => NOTE: if highlighting the parts in the `parts` story does not work out of the box, do not spend more effort on it but open a bug ticket to tackle it later.
#### Slots
  - [x] `content` - The expandable main content.
  - [ ] `expand-icon` - Optional expand icon to use instead of the default. Works best with `sd-icon`.
      - [x] used toggle-open and toggle-closed slots instead since we are using sd-links. (which already has a slot for icons)
#### Stories (besides the default)
- [x] `Inverted` - shows the inverted expandable
#### Sample
  - [x] `Background Variants` - shows usage on different backgrounds (neutral-100, white & primary-100)

### Technical Information
- [ ] "Show more" & "Show less" needs to be added to the translation.
- [x] This should have the same events and methods as `sd-accordion` (`open()`, `close()`, `sd-show`, `sd-after-show`, `sd-hide`, `sd-after-hide`
- [x] This should use the original HTML `details` `summary` element, as this enables it to automatically open the element when using the page search via `CMD + F`. For this it might be worth having a look in the new implementation in Shoelace: https://github.com/shoelace-style/shoelace/blob/next/src/components/details/details.component.ts

Instead of using the label attributes which we had for show and close the expandable we will integrate instance specific i18n. (https://github.com/solid-design-system/solid/issues/852)

### Open Questions towards design (@van-nguyen-ht @coraliefeil)
- [x] Figma file in general needs to be adopted according to the code implementation
- [x] Publish the Design Files from Figma 

## Subtasks
- [x] #1087
- [x] #1086 
- [x] #1088

## DoR
- [x] Item has business value
- [ ] All subtasks have been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] All subtasks have been closed

**Comment by mariohamann** [comment]
Some notes from my side:
- "Show more" should definitely be added to the translations. I'm not sure if the prop `expand-label` is then needed at all?
- Instead of setting the backgrounds, I would propose to try to use masking first: https://codepen.io/mariohamann/pen/zYXrEXy  This would enable usability on ANY background.

**Comment by van-nguyen-ht** [comment]
[Figma branch](https://www.figma.com/file/VTztxQ5pWG7ARg8hCX6PfR/branch/Ze8uVsiGtU4qyeCXgOvXy0/Solid-DS-%E2%80%93-Component-Library?type=design&node-id=1663-17726&mode=design&t=DRFZ8UPS1xomIIJZ-11)

Hi Karl here's the Figma build, the specs won't be added until end of the week since Sebastian is inspecting the plugins to approve usage.

**Comment by yoezlem** [comment]
@van-nguyen-ht are you still working on that feature? Because you move it from progress to ready but are still assaigned on it.

**Comment by van-nguyen-ht** [comment]
@yoezlem I'm done with it, just waiting for the plugin to add "hand-off".
