### ISSUE TITLE
feat: ✨ add sd-step & sd-step-group

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#304]
## User Story
As a user of the Solid Design System, I want to use a sd-step-group component for smooth navigation through task steps.

## Design Branch v1.0.0
https://www.figma.com/file/VTztxQ5pWG7ARg8hCX6PfR/branch/XQ86g7rO9VAF1zCeb3fMlh/Solid-DS-%E2%80%93-Component-Library?type=design&node-id=19206-26790&mode=design&t=JudeeRyagcu3nT60-0

## Documentation
https://www.figma.com/file/RQSSKJKUI90k21fK8DDK3q/Progress-Steps?type=design&node-id=1202-9493&mode=design&t=fD5NNuUK6I7kSPez-0
## Hand-off
https://www.figma.com/file/RQSSKJKUI90k21fK8DDK3q/Progress-Steps?type=design&node-id=6-4&mode=design&t=fD5NNuUK6I7kSPez-0

#### Props
| Status | Name | Type | Default | Description |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| <ul><li>[x] </li></ul>  | `size` | `lg` / `sm` | `lg` | Choose between `lg` for standard progress-steps or `sm` for tight spaces |
| <ul><li>[x] </li></ul>  | `orientation` | `horizontal` / `vertical` | `horizontal` | Choose between the 2 variants: horizontal & vertical. |
| <ul><li>[x] </li></ul>  | `state` | `waiting`/`finished`/`inProgress` | `waiting` | The indicator helps end users being aware of where they currently are within the process or task in relation to where they have been, and what to follow.  |
| <ul><li>[x] </li></ul>  | `noTail` | `boolean` | `false` | The border of the sd-step component.The border must extend 100% wide so that it can dock directly to the next sd-step component |
| <ul><li>[x] </li></ul>  | `label` | `string` | `` | Shows the label of the sd-step component. If you need to display HTML, use the `label` slot instead. |
| <ul><li>[x] </li></ul>  | `description` | `string` | `` | Shows the description of the sd-step component. If you need to display HTML, use the `description` slot instead. |

#### Parts (besides the shoelace parts)
  - [x] every other HTML element (depending on the HTML structure) => NOTE: if highlighting the parts in the `parts` story does not work out of the box, do not spend more effort on it but open a bug ticket to tackle it later.
#### Slots
  - [x] `label` - The progress-step label. Alternatively, you can use the `label` attribute.
  - [x] `default` - The sd-step description. Alternatively, you can use the `description` attribute.
#### Stories (besides the `default` story)
  - [x] `Orientation` - Shows both orientation (horizontal & vertical)
  - [x] `Size x State` - Show in a table both sizes with the different states

#### Props
| Status | Name | Type | Default | Description |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| <ul><li>[x] </li></ul>  | `size` | `lg` / `sm` | `lg` | The progress-steps group's size. This size will be applied to all child of sd-step |
| <ul><li>[x] </li></ul>  | `orientation` | `vertical` / `horizontal` | `horizontal` | The Group orientation. The orientation will be applied to all child of sd-step |

#### Parts (besides the shoelace parts)
  - [ ] every other HTML element (depending on the HTML structure) => NOTE: if highlighting the parts in the `parts` story does not work out of the box, do not spend more effort on it but open a bug ticket to tackle it later.
#### Stories (besides the `default` story)
  - [x] `Size` - (description)
  - [x] `Orientation` - Shows both orientations (horizontal & vertical)
#### Samples
  - [ ] `name` - add sd-media with an image inside the default slot (check the sample section for Figma Design Branch v1.0.0 Link)

 #### Methods
| Status | Name | Description |
| ------------- | ------------- | ------------- |
| <ul><li>[x] </li></ul>  | `setActiveStep` | Sets the active step-item |

### Open Questions towards design
- [ ] Question1
- [ ] Question2

## Technical Information
- [x] Steps that are completed must be clickable. The state from the previous one should also change back to waiting (check the click bahaviour here: https://ant.design/components/steps#steps-demo-clickable)
- [ ] For the noTail property the pseudo-element ::after could be a thing
    - [x] decided to move away from pseudo-elements since they need absolute styles and those do not work well when steps are used together
- [x] Focus state needs to be done for the sd-step component (state: finished). Please refer to the Figma branch v1.0.0 link für further clarification.
- [x] you can use sd-paragraph for the label and default slot.

## Subtasks
- [x] #547
- [ ] #1031
- [ ] #1030

## DoR
- [x] Item has business value
- [x] All subtasks have been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] All subtasks have been closed

**Comment by yoezlem** [comment]
Found this one: https://github.com/solid-design-system/solid/issues/744 which is a new variant for the sd-progress-step. Do we want to cover that in our story or leave it like it is?

**Comment by karlbaumhauer** [comment]
> Found this one: #744 which is a new variant for the sd-progress-step. Do we want to cover that in our story or leave it like it is?

this was excluded in a new ticket as it is not CL-migration related. I would leave it in a separate ticket.
