### ISSUE TITLE
feat: ✨ add sd-quickfact

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#305]
## User Story
As a user of the Solid Design System, I want to use the sd-quickfact component to present information in a more appealing and dynamic way, allowing for expandable content, so that I can engage with the content more effectively and have a better user experience.

## Description
https://www.figma.com/file/e8wQ2fYj7xZGbXKqXo9KUy/Quickfact-Group?type=design&node-id=1501-8528&mode=design&t=L55bFgMgKL1fDapo-0
-> open figma branch @van-nguyen-ht 

Refactor design component

- [x] Use sd-interactive for chevrons
- [x] Only use blue for chevrons (no more green indication)
- [x] Impl. default slot containing title and description and add query for desktop/mobile
- [x] For mobile change textblock to first line containing title and lines below containing description

## Hand-off
https://www.figma.com/file/e8wQ2fYj7xZGbXKqXo9KUy/Quickfact-Group?type=design&node-id=6-4&mode=design&t=L55bFgMgKL1fDapo-0

#### Props
| Status | Name | Type | Default | Description |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| <ul><li>[x] </li></ul>  | `open` | `boolean` | `false` | Indicates whether or not the quickfact is open. You can toggle this attribute to show and hide the default content inside the quickfact, or you can use the show() and hide() methods and this attribute will reflect the sd-quickfact's open state. If you have more than one sd-quickfact and opens one the other quickfacts should collapse (like in the accordion-group). |

#### CSS-Properties
  - [x] `name` - description
#### Parts (besides the shoelace parts)
  - [x] every other HTML element (depending on the HTML structure) => NOTE: if highlighting the parts in the `parts` story does not work out of the box, do not spend more effort on it but open a bug ticket to tackle it later.
#### Slots
  - [x] `default` - the quickfact main content. If this slot isn't empty an sd-icon chevron should appear.
  - [x] `icon` - The quickfact's icon. Please mentioned it in the docs that content-icon should be used here.
  - [x] `summary` - The quickfact's summary.
  - [x] `expand-icon` - Optional expand icon to use instead of the default. Works best with <sd-icon>.
  - [x] `collapse-icon` - Optional collapse icon to use instead of the default. Works best with <sd-icon>.
#### Stories (besides the `default` story)
  - [x] `States x Content` - A quickfact can either be collapsed or open. Show both way -> with content and without.
  - [x] `Desktop vs. Mobile` - Show both designs here.
#### Samples
  - [x] `Grouping` - Utilize multiple sd-quickfacts (gaps between can be considered in the hand-off) and fill all slots. Please take a deeper look on our designs for this purpose.

 #### Methods
| Status | Name | Description |
| ------------- | ------------- | ------------- |
| <ul><li>[x] </li></ul>  | `show` | Shows the content of the quickfact. |
| <ul><li>[x] </li></ul>  | `hide` | Hides the content of the quickfact. |

 #### Events
| Status | Name | Description |
| ------------- | ------------- | ------------- |
| <ul><li>[x] </li></ul>  | `sd-show` | Emitted when the quickfact opens. |
| <ul><li>[x] </li></ul>  | `sd-after-show` | Emitted after the quickfact opens and all animations are complete. |
| <ul><li>[x] </li></ul>  | `sd-hide` | Emitted when the quickfact opens.  |
| <ul><li>[x] </li></ul>  | `sd-after-hide` | Emitted after the quickfact closes and all animations are complete. |

### Technical Information
- [x] Ensure that the sd-quickfact has two different designs (optic) for desktop and mobile. Keep in mind to use the mobile first approach!
- [x] collapse-icon and expand-icon can only be filled if default slot isn't empty (can be detected from the host element).
- [x] When a sd-quickfact is selected, the main slot will only be displayed within the width of that parentElement, no matter how much sd-quickfact's we have. Please check also if the component have content inside the slot, if so use the parentElement.
- [x] The user is able to open only one sd-quickfact at a time. The previously opened one will then be automatically closed (check the accordion-group for the implementation).
- [x] Check if its possible to use the `summary` and `details` HTML tags (accessible)

## Subtasks
- [x] #1014
- [x] #1015
- [x] #1016

## DoR
- [x] Item has business value
- [x] All subtasks have been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] All subtasks have been closed

**Comment by coraliefeil** [comment]
Pls see pre-refined description and update design comp accordingly. So we can prepare it best for refinement and then coding. Thank you

**Comment by coraliefeil** [comment]
See also current comp in the cms library
https://cms-components.fe.union-investment.de/latest/storybook/index.html?path=/story/cms-components-cms-quickfact--configurable&globals=backgrounds.value:!hex(F6F6F6)

**Comment by van-nguyen-ht** [comment]
Hello @coraliefeil here's the [Figma Branch ](https://www.figma.com/file/eJJKt0CGHUpkx6RKK7dJOG/sd-quickfact-group-V.0.0.2?type=design&node-id=1664-16059&mode=design)

**Comment by coraliefeil** [comment]
Added some comments. Thanks a lot.
