### ISSUE TITLE
feat: ✨ add `sd-range`

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#306]
## User Story
As a user of the Solid Design System, I would like to utilize a range component in order to provide a possibility to select a range between two values, as well as have additional information about the scale and steps on these values displayed in a brand conform and accessible way.

## Documentation / Hand-off
[Figma Branch](https://www.figma.com/file/iXoxWhTBjKK8WxMzPkRyxR/sd-range-V.1.0.0?type=design&node-id=19569-89&mode=design)

The `sd-range` contains a parent and a child component. In case the user needs only one single knob, the child component `sd-range-knob` is not needed. The `sd-range` will add a single knob by itself.
In case the user needs multiple knobs (currently only 2 knobs are communicated), the `knobs` slot is supposed to be used and **_2 knobs_** need to be added. 

#### Props
| Status | Name | Type | Default | Description |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| <ul><li>[ ] </li></ul>  | `label` | `string` | `Label` | Simple text to define the label.|
| <ul><li>[ ] </li></ul>  | `help-text` | `string` | `Help-text` | Simple text to define an optinal helper text underneath the component.|
| <ul><li>[ ] </li></ul>  | `offset` | `number` | `none` | Defines the offest value of the range starting point.|
| <ul><li>[ ] </li></ul>  | `min` | `number` | `0` | Defines the sart value of the range.|
| <ul><li>[ ] </li></ul>  | `max` | `number` | `100` | Defindes the end value of the range.|
| <ul><li>[ ] </li></ul>  | `step` | `number` | `1` | Defines the step granularity of the knobs.|
| <ul><li>[ ] </li></ul>  | `value` | `number` | `none` | Defines/describes the value of the input field itself.|
| <ul><li>[ ] </li></ul>  | `no-tooltip` | `boolean` | `false` | Hides the tooltip on the knobs. |
| <ul><li>[ ] </li></ul>  | `disabled` | `boolean` | `false` | Disables the range component.|

#### CSS-Properties
  - [ ] `track-offset` -This influences the styling of the offset – maybe this is easier than an attribute, but we would have to chack (Shoelace's solution looks quite straightforward) – maybe this is useful in the knob as well, but I'm not sure
#### Parts (besides the shoelace parts)
  - [ ] every HTML element => NOTE: if highlighting the parts in the `parts` story does not work out of the box, do not spend more effort on it but open a bug ticket to tackle it later.
#### Slots
  - [ ] `label` - HTML content and/or complex lable structure can be added here.
  - [ ] `default` - HTML content for additional description and/or values on the range.
  - [ ] `help-text` - HTML content and/or complex help-text structure can be added here.
  - [ ] `ticks` - Slot for additional tick elements.
  - [ ] `knobs` - Slot for multiple knobs.
#### Stories (besides the `default` story)
  - [ ] `offset & disabled` - showing a range with offset and in disabled state.
  - [ ] `mouseless` - showing the keyboard functionality
  - [ ] `slots` - showing all the slots of the range.
  - [ ] `parts` - showing all the CSS parts of the range.
#### Templates
  - [ ] `ticks` - showing a template with a simple tick
  - [ ] `label & help-text` - showing a complex label and help-text slot usage to display additional min/max labels ("Mehr/Weniger Riskio")

### Technincal Information
We definitely should start with the Synergy solution: https://synergy-design-system.github.io/?path=/docs/components-syn-range--docs

- The only thing which is missing here is the inverted state. So please don't forget that.

## DoR
- [x] Item has business value
- [x] All subtasks have been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] All subtasks have been closed

**Comment by karlbaumhauer** [comment]
@coraliefeil and @mariohamann pls fill in the missing infos / answer the open questions. After that, you can move the ticket into the refinement column.

**Comment by mariohamann** [comment]
Removed myself, moved to be refined and removed pre-refinement label.

**Comment by yoezlem** [comment]
FYI: Because the component will be very complex with the multi-range function, I have decided, just like with the datepicker component, to label this as a new feature and remove the CL-Migration label. If you have any questions, feel free to reach out to me.
