### ISSUE TITLE
docs: 📚 change defaults for sd-teaser

### ISSUE THREAD

**Issue by mariohamann** [solid-design-system/solid#349]
## Description

I would suggest to use "white border-neutral-300" in teaser showcase instead of the light blue variant, as the latter is supposed to be used on blue backgrounds (and therfore elads to strange paddings e. g. for the meta text), but the outlined one can be used standalone. 

### Current
![CleanShot 2023-08-22 at 22 19 56@2x](https://github.com/solid-design-system/solid/assets/26542182/d900f1e1-264e-44b9-8060-1d8949d9c76b)

### Proposal
![CleanShot 2023-08-22 at 22 19 28@2x](https://github.com/solid-design-system/solid/assets/26542182/40761ba2-89fd-4513-9937-b04a0da55cc8)

### TODO:
- [x] change defaults in the slot story
- [x] revise the "excludes" in the stories
- [x] copy comment from "breakpoint" property to the sample in the docs

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [x] Documentation has been created/updated (if applicable)
- [x] Migration Guide has been created/updated (if applicable)
- [x] Relevant stories (Features, A11y) are created/updated
- [x] Implementation works successfully on `feature` branch
