### ISSUE TITLE
feat: ✨ add sd-media

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#388]
## User Story
As a [PERSONA] of the Solid Design System, I would like to [REQUIRE], as well as [FURTHER_REQUIREMENT],
so that [PRODUCT_VALUE], and [FURTHER_PRODUCT_VALUE].

## API
[LINK TO FIGMA]
## Hand-off
[LINK TO FIGMA]

### Components detailed requirements
- [ ] Props, CSS-Properties, Parts & Slots
  - [ ] tbd
- [ ] Stories
  - [ ] tbd

## TODO:
clarify if copyright comes from sd-image/video or sd-media

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by yoezlem** [comment]
This seems to be a duplicate of #276. Shall we close it?
