### ISSUE TITLE
docs: 📚 improve changelog

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#414]
## Description
Other providers seem to be able to provide well structured changelogs for third-party-tools like renovate:

![image](https://github.com/solid-design-system/solid/assets/48211526/b85e61e9-69f3-4873-8b7d-7d6e7835c994)

Our changelog in the renovate PR looks like this: 

![Image](https://github.com/solid-design-system/solid/assets/48211526/fdf65aca-774b-4dfa-8907-1cc22dbb3fd0)

It would be nice to provide some more details here.

## ToDo:

- [ ] research how to provide more details in the changelog
- [ ] share with the team for further implementation

## Where to put the documentation
GitHub

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [] Item dependencies have been identified N/A

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by karlbaumhauer** [comment]
@yoezlem yes, indeed... ;) just changed it and added a most recent screenshot from a renovate PR.
