### ISSUE TITLE
chore: 🔧 switch Tokens Studio default branch to main

### ISSUE THREAD

**Issue by mariohamann** [solid-design-system/solid#531]
## User Story
As a maintainer of the Solid Design System, I would like to get fast updates from Figma tokens, when they were created and approved.

### Suggested Solution
Currently design merges to an own outdated `figma-tokens` branch in the solid repo. This setting has to be changed to the protected `main` branch.

This offers the possibility to create new feature branches (in Figma) for token updates using the `main` branch as basis. 
This creates a PR in Figma to the `main` branch and a respective PR in GitHub automatically.
Therewith the development can review the changes in a PR to the `main` directly and no update from the `figma-tokens` towards the `main` branch is necessary anymore. 

## Technical Information

![Image](https://github.com/solid-design-system/solid/assets/41894356/10d460e6-0aa2-4ba5-8b05-2b6a1550df38)

## Tasks
- [x] Update the `main` branch from the `figma-tokens` branch => NOTE: even folder structure needs to be updated => copy paste to `main` branch might be necessary.
- [x] In Figma the `main` branch needs to be set as basis
- [ ] A detailed explanation and description about the PR title naming convention according to the [development standards](https://github.com/solid-design-system/solid/blob/main/CONTRIBUTING.md#commit-messages) needs to be added to Figma
- [x] `figma-tokens` branch needs to be deleted in the solid repo

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Implementation works successfully on `feature` branch
- [x] Onboarding for Figma maintainers has been updated

**Comment by Vahid1919** [comment]
This ticket was accidentally closed, so I am reopening it. Since tokens are now updated, I believe the next tasks are left for @solid-design-system/design.  I will assign @van-nguyen-ht and unassign myself. 

Let me know if there is more work here to be done :)

**Comment by van-nguyen-ht** [comment]
@Vahid1919 Hi Vahid, I've 
-switched the branch in Figma Tokens from "figma-tokens" into "main" and 
-updated the onboarding in Figma
so I'm handing the ticket back to you

**Comment by Vahid1919** [comment]
Hey @van-nguyen-ht!
One of the tasks is still unchecked above("A detailed explanation and description about the PR title naming convention...")

I would check myself but I am having issues accessing Figma. Is that task completed? If so, then we can close this ticket.

**Comment by mariohamann** [comment]
Could you check our dev README if it is sufficient for design? We have a part there, maybe we should add something like "add tokens", "fix tokens" or similar.

**Comment by Vahid1919** [comment]
> Could you check our dev README if it is sufficient for design? We have a part there, maybe we should add something like "add tokens", "fix tokens" or similar.

@mariohamann Can you give me more context here. Do we want to tell designers how to add tokens in the README?
