### ISSUE TITLE
feat: sd-combobox

### ISSUE THREAD

**Issue by coraliefeil** [solid-design-system/solid#548]
## User Story
As a user of the Solid Design System, I would like to be able to select multiple items by typing parts of the item label and selecting one or multiple items, so that I don't have to scroll through long lists and pick single items.

## Documentation
[[LINK TO FIGMA]](https://www.figma.com/design/VTztxQ5pWG7ARg8hCX6PfR/branch/W0LTcrsplIFyHJonYNyqsG/Solid-DS-%E2%80%93-Component-Library?node-id=29661-6985&node-type=section&t=C7OgDla05uoKaqZf-11)

#### Attributes
| Status | Name | Type | Default | Description |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| <ul><li>[ ] </li></ul>  | `label` | `string` | `''` | The combobox's label. If you need to display HTML use the `label` slot instead |
| <ul><li>[ ] </li></ul>  | `help-text` | `string`| `''` | The combobox's help text. If you need to display HTML, use the `help-text` slot instead. |
| <ul><li>[ ] </li></ul>  | `name` | `string` | `''` | The name of the combobox, submitted as a name/value pair with form data. |
| <ul><li>[ ] </li></ul>  | `value` | `string` | `''` | The current value of the combobox, submitted as a name/value pair with form data. |
| <ul><li>[ ] </li></ul>  | `size` | `sm` / `md` / `lg` | `lg` | The combobox's size. |
| <ul><li>[ ] </li></ul>  | `placeholder` | `string` | `''` | Placeholder text to show as a hint when the combobox is empty. |
| <ul><li>[ ] </li></ul>  | `disabled` | `true` / `false` | `false` | Disables the combobox control. |
| <ul><li>[ ] </li></ul>  | `clearable` | `true` / `false` | `false` | Adds a clear button when the combobox is not empty. |
| <ul><li>[ ] </li></ul>  | `open` | `true` / `false` | `false` | Indicates whether or not the combobox is open. You can toggle this attribute to show and hide the listbox, or you can use the show() and hide() methods and this attribute will reflect the combobox's open state. |
| <ul><li>[ ] </li></ul>  | `hoist` | `true` / `false` | `false` | Enable this option to prevent the listbox from being clipped, when the component is placed inside a container with overflow: auto|scroll. Hoisting uses a fixed positioning strategy that works in many, but not all, scenarios. |
| <ul><li>[ ] </li></ul>  | `placement` | `top` / `bottom` | `bottom` | The preferred placement of the combobox's menu. Note that the actual placement may vary as needed to keep the listbox inside of the viewport. |
| <ul><li>[ ] </li></ul>  | `getOption` | `string` | `` | A function that customizes the rendered option. The first argument is the option, the second is the query string, which is typed into the combobox. The function should return either a Lit TemplateResult or a string containing trusted HTML to render in the shown list of filtered options. |

#### CSS-Properties
  - [x] `name` - description
  - [ ] `name` - description

#### Parts
  - [x] `form-control` - description
  - [ ] `form-control` - The form control that wraps the label, combobox, and help text.
  - [ ] `form-control-label` - The label's wrapper.
  - [ ] `form-control-input` - The combobox's wrapper.
  - [ ] `form-control-help-text` - The help text's wrapper.
  - [ ] `combobox` - The container the wraps the prefix, combobox, clear icon, and expand button.
  - [ ] `prefix` - The container that wraps the prefix slot.
  - [ ] `suffix` - The container that wraps the suffix slot.
  - [ ] `display-input` - The element that displays the selected option's label, an `<input>` element.
  - [ ] `listbox` - The listbox container where the options are slotted and the filtered options list exists.
  - [ ] `filtered-listbox` - The container that wraps the filtered options.
  - [ ] `clear-button` - The clear button.
  - [ ] `expand-icon` - The container that wraps the expand icon.
  - [ ] every other HTML element (depending on the HTML structure) => NOTE: if highlighting the parts in the `parts` story does not work out of the box, do not spend more effort on it but open a bug ticket to tackle it later.

#### Slots
  - [x] `default` - The listbox options.
  - [ ] `label` - The combobox's label. Alternatively, you can use the `label` attribute.
  - [ ]  `help-text` - The combobox's label. Alternatively, you can use the `help-text` attribute.
  - [ ] `left` - Used to prepend a presentational icon or similar element to the combobox.
  - [ ] `right` - Used to prepend a presentational icon or similar element to the combobox.
  - [ ] `clear-icon` - An icon to use in lieu of the default clear icon.
  - [ ] `expand-icon` - The icon to show when the control is expanded and collapsed. Rotates on open and close.

#### Properties
  - [ ] `defaultValue` - The default value of the form control. Primarily used for resetting the form control.
  - [ ] `validity ` - Gets the validity state object
  - [ ] `validationMessage ` - Gets the validation message

#### Events
- [ ] `sd-change` - Emitted when the control's value changes.
- [ ] `sd-clear` - Emitted when the control's value is cleared.
- [ ] `sd-input` - Emitted when the control receives input.
- [ ] `sd-focus` - Emitted when the control gains focus.
- [ ] `sd-blur` - Emitted when the control loses focus.
- [ ] `sd-show` - Emitted when the combobox's menu opens.
- [ ] `sd-after-show` - Emitted after the combobox's menu opens and all animations are complete.
- [ ] `sd-hide` - Emitted when the combobox's menu closes.
- [ ] `sd-after-hide` - Emitted after the combobox's menu closes and all animations are complete.
- [ ] `sd-invalid` - Emitted when the form control has been checked for validity and its constraints aren't satisfied.
- [ ] `sd-error` - Emitted when the combobox menu fails to open.

#### Methods
- [ ] `show` - Shows the listbox. If it is not possible to open the listbox, because there are no appropriate filtered options, a syn-error is emitted and the listbox stays closed.
- [ ] `hide` - Hides the listbox.
- [ ] `checkValidity` - Checks for validity but does not show a validation message. Returns true when valid and false when invalid.
- [ ] `getForm` - Gets the associated form, if one exists.
- [ ] `reportValidity` - Checks for validity and shows the browser's validation message if the control is invalid.
- [ ] `setCustomValidity` - Sets a custom validation message. Pass an empty string to restore validity.
- [ ] `focus` - Sets focus on the control.
- [ ] `blur` - Removes focus from the control.

#### Stories
  - [ ] `Default` - The combobox suggests items based on the user input.
  - [ ] `Labels` - Use the label attribute to give the combobox an accessible label. For labels that contain HTML, use the label slot instead.
  - [ ] `Help Text` - Add descriptive help text to a combobox with the help-text attribute. For help texts that contain HTML, use the help-text slot instead.
  - [ ] `Placeholder` - Use the placeholder attribute to add a placeholder.
  - [ ] `Focus` - The focus attribute provides feedback to the users, informing them that the combobox component is ready for use.
  - [ ] `Simple Suggests` - A simple suggestions list shows the user a filtered list.
  - [ ] `Highlight Query` - The filtered options shown in the list can be customized by passing a function to the getOption property. Your function can return a string of HTML, a Lit Template, or an HTMLElement. The getOption() function will be called for each option. The first argument is an <syn-option> element and the second argument is the query string.
Remember that the options are rendered in a shadow root. To style them, you can use the style attribute in your template or you can add your own parts and target them with the ::part() selector.
**Note:** Be sure you trust the content you are outputting! Passing unsanitized user input to getOption() can result in XSS vulnerabilities.
  - [ ] `Grouping Query` - Use <sd-optgroup> to group <sd-option>`s visually.
  - [ ] `Suggestion Container Height` - The height of the filtered options list can be customized by setting the max-height on the listbox part of the combobox.
  - [ ] `Clearable` - Add the clearable attribute to add a clear button when the combobox has content.
  - [ ] `Disabled` - Use the disabled attribute to disable a combobox.
  - [ ] `Sizes` - Use the size attribute to change a combobox size.
  - [ ] `Invalid` - The invalid status is used to warn the user that the combobox is invalid. For example, if the entry is mandatory.
  - [ ] `Icons` - Use the prefix and suffix slots to add icons.
  - [ ] `Async Options` - It is possible to add options dynamically to the combobox e.g. if the option values need to be fetched asynchronously from a remote server or API.
  - [ ] `Custom Filters` - A custom filter can be applied by passing a filter function to the filter property. This filter() function will be called for each option. The first argument is an <sd-option> element and the second argument is the query string.

#### Templates
  - [ ] `name` - description
  - [ ] `name` - description

## Technical Information
- [ ] Copy the `<syn-combobox>` (https://synergy-design-system.github.io/?path=/docs/components-syn-combobox--docs) into our repo at packages/components/src/components 
- [ ] The validation behavior of the Combobox component must be identical to the validation logic implemented in the sd-input component. This includes input validation rules, error handling, and displaying validation messages.
- [ ] The current `<syn-Combobox>` does not support multi-select. This functionality needs to be implemented on our side. For reference, you can look at the `<sd-select>` component, where we have already implemented the multi-select feature. It may be possible to adapt the existing logic from there

### Open Questions towards design
- [ ] Question1
- [ ] Question2

## Subtasks
- [x] #1388
- [x] #1387
- [x] #1686 
- [x] #1386

## DoR
- [x] Item has business value
- [ ] All subtasks have been estimated by the team
- [x] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] All subtasks have been closed

**Comment by yoezlem** [comment]
Here is another Request for a combobox: https://github.com/solid-design-system/solid/issues/1271

**Comment by yoezlem** [comment]
Request from: 
- UI Portal
- UAM
- IK Online

Needs discussion

**Comment by yoezlem** [comment]
@coraliefeil @mariohamann @karlbaumhauer please fill in the missing things.

**Comment by coraliefeil** [comment]
@yoezlem & @mariohamann pls align on multi select feature ... THX

**Comment by yoezlem** [comment]
@DanielHargesheimer here is the Audit for the combobox:

## Comment

**Problem:** The [[default example](https://solid-design-system.fe.union-investment.de/x.x.x/storybook/?path=/docs/components-sd-input--docs#value)](https://solid-design-system.fe.union-investment.de/x.x.x/storybook/?path=/docs/components-sd-input--docs#value) has no accessible name and no visual label.

**Solution:** At least add an accessible name. Better: both.

---

**Problem:** The “Clear entry”-button is not accessible via the keyboard. That’s probably on purpose, but I don’t see why it shouldn’t be focusable.

**Solution:** Remove the `tabindex`-attribute.

---

**Problem:** Invalid fields don't semantically indicate that they're invalid.

**Solution:** Put `aria-invalid="true"` on invalid fields.

---

**Problem:** Options in grouped lists are inaccessible via screen reader (VO, NVDA, JAWS, and TALKBACK). 

I'm having a hard time debugging this component. I'm not 100% sure what causes the problems. I've tested [[another implementation](https://cauldron.dequelabs.com/components/Combobox#grouping)](https://cauldron.dequelabs.com/components/Combobox#grouping), which works well. Please consider using their structure.

**Solution:** Adapt markup.

```html
<label for="input" id="label">Countries</label>
<input type="text" id="input" role="combobox" aria-autocomplete="list" aria-controls="listbox" aria-expanded="true" aria-haspopup="listbox">

<ul role="listbox" aria-labelledby="label" id="listbox">
  <ul role="group" aria-labelledby="listbox-group-label1">
    <li role="presentation" id="listbox-group-label1">North America</li>
    <li id="combobox-option39" role="option" aria-selected="false">Canada</li>
    <li id="combobox-option40" role="option" aria-selected="false">Mexico</li>
    <li id="combobox-option41" role="option" aria-selected="false">United States</li>
  </ul>
  <ul role="group" aria-labelledby="listbox-group-label2" aria-hidden="false">
    <li role="presentation" id="listbox-group-label2">South America</li>
    <li id="combobox-option43" role="option" aria-selected="false">Argentina</li>
    <li id="combobox-option44" role="option" aria-selected="false">Bolivia</li>
    <li id="combobox-option45" role="option" aria-selected="false">Brazil</li>
  </ul>
 </ul>
```

## Notes

- Combobox support and behavior are inconsistent across screen readers and browsers. Talkback, for example, doesn't support them at all. Keyboard shortcuts in VO are different than in NVDA. Prefer native selects over comboboxes, if possible.
- The prefixes and suffixes are just strings inside the component. They're not connected to the input field. The generic examples of the components don't explain how you're supposed to use them, but I assume that the prefixes and suffixes should be part of the accessible name.
- Disabled combobox: See [[sd-button](https://www.notion.so/sd-button-104f3f6e1bc0800b9f72d2a046316ec3?pvs=21)](https://www.notion.so/sd-button-104f3f6e1bc0800b9f72d2a046316ec3?pvs=21) . Everything I wrote there about disabling form elements applies here as well.

## Additional resources

[[Deque Cauldron React](https://cauldron.dequelabs.com/components/Combobox#grouping)](https://cauldron.dequelabs.com/components/Combobox#grouping)

**Comment by coraliefeil** [comment]
I’ve refined the [design component](https://www.figma.com/design/VTztxQ5pWG7ARg8hCX6PfR/branch/W0LTcrsplIFyHJonYNyqsG/Solid-DS-%E2%80%93-Component-Library?node-id=29661-6985&node-type=section&t=C7OgDla05uoKaqZf-11). Pls have a look @DanielHargesheimer 

Prefix Suffix Text And Icons - Use the prefix and suffix slots to add text and icons.
-> I think we don’t need this in our context.

Do we still have the Options selected (3) in the field or do we always have option tags in the field?

**Comment by mariohamann** [comment]
As it's the same as the input, we at least need those prefixes as `icon-left` and `icon-right`.

The thing is: We still have to be able to type – on either the left or the right of the selcted things. Having a "text" there could be irritating, as it would interfere with the writing. I therefore would maybe even opt-in to tags first?

**Comment by coraliefeil** [comment]
@DanielHargesheimer @smfonseca @mariohamann @MartaPintoTeixeira 
After some research and based on our discussion I suggest we go into the direction of vaadin’s combobox.

See [figma](https://www.figma.com/design/VTztxQ5pWG7ARg8hCX6PfR/branch/W0LTcrsplIFyHJonYNyqsG/Solid-DS-%E2%80%93-Component-Library?node-id=29661-7024&node-type=frame&t=nh2T7Lsn205VcULi-11)

**Comment by coraliefeil** [comment]
I would use maxLength with 15 characters max for tags.
