### ISSUE TITLE
feat: ✨ add icons to sd-textarea

### ISSUE THREAD

**Issue by saemik94** [solid-design-system/solid#571]
## User Story
As a user of the Solid Design System, I need icons for the `sd-textarea` to indicate whether the field is valid or not, because a purely color distinction is not sufficient for accessibility

## Hand-off
https://www.figma.com/file/07Bzd23A0QSrSWiXy6w2uM/Text-Area?node-id=0%3A1&mode=dev
https://www.figma.com/file/VTztxQ5pWG7ARg8hCX6PfR/branch/AJkclhNGizzmcYGicL6aHc/Solid-DS-%E2%80%93-Component-Library?type=design&node-id=14368-8209&mode=design&t=MSTvEjVeckPwhTVC-0

## Technical note
The current design is not technically feasible. This is because the text area does not allow another element to be placed in it. Therefore, the icon simply has to be displayed in front of the area and this leads to the following problems:
- The text cannot flow around the icon.
- If the icon has a transparent background, you can see the text and icon on top of each other.
- If the icon has a background, this does not automatically match the background of the text area (hover, focus, disabled...) and therefore does not work.

### Components detailed requirements
- [ ] The state of the "sd-textarea" field is represented by an icon
  - [ ] Success
  - [ ] Invalid

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Brand approval (if neccessary)
- [ ] Figma documentation file incl. hand-off has been created/updated (if applicable)
- [ ] Tokens have been applied/updated (if applicable)
- [ ] Crosslinks are created/updated
- [ ] Implementation works successfully on `figma` branch
- [ ] Published in Figma and communicated in release notes
- [ ] Issues for dependencies have been created (if neccessary)

**Comment by coraliefeil** [comment]
@MartaPintoTeixeira pls check if the issues mentioned still exist or have alerady been fixed by latest a11y adjustments. Thank you

**Comment by MartaPintoTeixeira** [comment]
<img width="1244" alt="Image" src="https://github.com/user-attachments/assets/3bc074e8-a0be-4724-9d62-cb007e5a868a" />

I believe this issue has already been adresseed in a11y adjustments. See img above. @coraliefeil

**Comment by MartaPintoTeixeira** [comment]
<img width="1601" alt="Image" src="https://github.com/user-attachments/assets/2ea432fe-ff3d-4bc1-ae6e-56d1fc8438be" />
Issue is still not solved neither in code or figma.

**Comment by yoezlem** [comment]
blocked by #1784

**Comment by coraliefeil** [comment]
Icons are shown which solves the initial issue here.

But the valid and invalid textareas still need to solve the issue that text is partially cut off due to the check-/error-icon overlaying the text content.

I’m closing this issue here and open up a new fix issue.
