### ISSUE TITLE
feat: ✨ add sd-menu sd-menu-item

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#594]
## User Story
As a user of the Solid Design System, I would like to have a `sd-menu` and `sd-menu-item` added to the library, so that I can build a interactive application dropdown menu with.

## API
[LINK TO FIGMA]
## Hand-off
[LINK TO FIGMA]
## Documentation
[LINK TO FIGMA]

### Technical information
`sd-menu` is not to be meant as a navigation menu but as an application menu usually in a dropdown, which opens up a bunch of functions and has a completely different keyboard behavior in comparison to a link list in a menu.

Check out for reference: https://www.w3.org/WAI/tutorials/menus/application-menus/ https://shoelace.style/components/menu https://shoelace.style/components/dropdown

Our `sd-dropdown` component is already to handle this keyboard behavior and everything. We just need a matching design for the `sd-menu` and `sd-menu-item`, ideally with a similar interface to that of Shoelace.

If this will never be implemented, we should remove all logic in the `sd-dropdown` which belongs to the `sd-menu`, including types and tests.

#### Props
| Status | Name | Type | Default | Description |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| <ul><li>[ ] </li></ul>  | `name` | `type` | `default` | description |
| <ul><li>[ ] </li></ul>  | `name` | `type1` / `type2` | `default` | description |

#### CSS-Properties
  - [ ] `name` - description
  - [ ] `name` - description
#### Parts
  - [ ] `name` - description
  - [ ] `name` - description
#### Slots
  - [ ] `name` - description
  - [ ] `name` - description
#### Stories (besides the `default` story)
  - [ ] name (description)
  - [ ] name (description)
#### Samples
  - [ ] `name` - description
  - [ ] `name` - description

### Open Questions towards design
- [ ] Question1
- [ ] Question2

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by karlbaumhauer** [comment]
design is covered with #559

**Comment by yoezlem** [comment]
Duplicate #1763

**Comment by yoezlem** [comment]
Will close this one (duplicate)
