### ISSUE TITLE
docs: 📚 move `Component API` section in Figma

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#612]
## Description
To improve the documentation and the access to it, the `Component API` section of each component in Figma should be moved to another section.
The current idea is to place it next to the Hand-off, as it fits better content wise.

## Task
- [x] elaborate a good position for the API section => already moved to the hand-off in all new components
- [x] move API section in all components

## Where to put the documentation
Figma
## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Implementation works successfully on `feature` branch
