### ISSUE TITLE
feat: ✨ add sd-breadcrumb

### ISSUE THREAD

**Issue by mariohamann** [solid-design-system/solid#684]
## User Story
As a user of the Solid Design System, I would like to have a breadcrumb components, so that I can easily provide responsive and accessible breadcrumbs.

## Documentation
https://www.figma.com/file/hLm8x4MIBoErSfTp5VexgO/sd-breadcrumb-V.0.0.1?type=design&node-id=6646-28793&mode=design

Follow up of https://github.com/solid-design-system/figma/issues/60

### Component name
`sd-breadcrumb` & `sd-breadcrumb-item`

### Components detailed requirements
Everything in the figma design.
Changes (which also need to be made in Figma):
- sd-breadcrumb: 
  - adding the separator
  - taking care of truncation if space is not enough
  - handles mobile view (on first level, only showing "current" page) => In case page names are too long to be shown, we cut it off. **->> no, on mobile we need to show the link to the upper page, not show current page**
  - For truncation, we should use https://github.com/synergy-design-system/synergy-design-system/blob/main/packages/components/src/components/prio-nav/prio-nav.component.ts and https://synergy-design-system.github.io/?path=/story/components-syn-prio-nav--priority-menu&globals=viewport:defaultViewPort as a basis.

- sd-breadcrumb-item: 
  - separator removed
  - "disabled" renamed to "current" (investigate "current" page item specs on WCAG - needs to be a link? can be text?)
  - truncated removed
  - **unlcear** if icon option is needed if separator and chevron is handled in the _sd-breadcrumb_
  - "mobile" removed from the item

#### Notes
It would be great to have as less JS as possible.

In general this component offers much lest in comparison to the one of Shoelace. Maybe copying even doesn't make so much sense. At least we should have a look on the DOM structure, aria roles etc.

## DoR
- [x] #1854
- [x] All subtasks have been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] All subtasks have been closed

**Comment by mariohamann** [comment]
@karlbaumhauer Ready for pre-refinement.

**Comment by coraliefeil** [comment]
Idea is to only code sd-breadcrumb-item and add the group with feat. as template.
