### ISSUE TITLE
feat: ✨ add sd-status-badge (CSS style)

### ISSUE THREAD

**Issue by coraliefeil** [solid-design-system/solid#775]
## User Story
As a stakeholder of the Solid Design System, I would like to have a status badge which I can use to show a certain status in my interface. 

## Documentation & Hand-off
[Figma Master Component](https://www.figma.com/design/VTztxQ5pWG7ARg8hCX6PfR/Solid-DS-%E2%80%93-Component-Library?node-id=16050-1114&t=It5ORx8vstXU46d0-11)
[Figma Docs](https://www.figma.com/design/YDktJcseQIIQbsuCpoKS4V/Component-Docs?node-id=2560-24438&t=r9lpHD6zDj2OvevZ-11)
[Figma Template](https://www.figma.com/design/YDktJcseQIIQbsuCpoKS4V/Component-Docs?node-id=3274-19607&t=r9lpHD6zDj2OvevZ-11)

### Components detailed requirements
The component consists of a colored circle background with a white status asset on top.
Status assets are another, internal categorie we use as icons in our solid components.
Status assets are neither content icons nor system icons and need to be implemented as such in Storybook.
Status assets can be swapped according to the desired status (exclamation, clock, ...)
Additionally a text can be shown on the right hand side (maybe only shown as a sample?)

#### Styles
| Status | Name | Type | Default | Description |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| <ul><li>[ ] </li></ul>  | `&--variant` | `success` / `warning` / `error` / `info` | 

#### CSS-Properties
  - [ ] `name` - description
  - [ ] `name` - description
#### Parts (besides the shoelace parts)
  - [ ] every other HTML element (depending on the HTML structure) => NOTE: if highlighting the parts in the `parts` story does not work out of the box, do not spend more effort on it but open a bug ticket to tackle it later.
#### Stories (besides the `default` story)
  - [ ] `Variants` - (description)
#### Samples
  - [ ] `name` - description

### Open Questions towards design
- [ ] Question1
- [ ] Question2

## Subtasks
- [x] #1047 
- [ ] #1046 
- [x] #1048

## DoR
- [x] #1843
- [x] #1845
- [x] #1844
- [x] Item dependencies have been identified

## DoD
- [ ] All subtasks have been closed
