### ISSUE TITLE
feat: ✨ extend `sd-brandshape` with outline variants + image

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#792]
## User Story
As a user of the Solid Design System, I would like to have the `sd-brandshape` extended with outline variants, so that I can migrate from `ui-container` with activated `stylized` property, and cover all defined color variants from [cd-toolbox](https://cd.union-investment.de/grundlagen/Basiselemente/Markenform#:~:text=zu%20diesem%20wahren.-,Flexible%20Objekt%2DStile,-Die%20Markenform%20k%C3%B6nnen).

### Suggested Solution
Using drop-shadow like proposed earlier (see CodePen https://codepen.io/mariohamann/pen/RwOrLEP) doesn't work, as this would always need a background. Therefore we go the route of the current component-library component: We utilize CSS `skewing` how it's defined there.

The important part is: We only do this, if the variant is `border-*` or `image`. For all other (current) variants, we stay with the current solution. The reason is: While `skewing` offers more flexibility, the other one is more exact in terms of brand definitions. In this way we can offer the best from both world. Furthermore CMS team is already using the component and we shouldn't break behaviour for them which they might rely on.

- [x] new variants
Furthermore, we will only continue the following border variants (as mentioned in the CD-Toolbox):
- border-primary
- border-white
- image (could be recognized automatically when image slot is filled)
> Note: `border-green-blue-gradient` (not applicable in web) & `border-accent` removed by brand

For the image it might be the easiest and most performant to have an `<slot name="image"><img.../></slot>` to have the image already in the LightDOM. You can have a loon in the `ui-container` component in the `stylized` variant how it's done there.

The current solution to hide specific parts should ideally still work for the border-variants as well. Definitely the slot behaviour should stay. If there are concrete problems, please discuss in team.

- [x] migration guide
The current migration guide from #789 needs to be adopted and ALL limitations or changes need to be documented carefully.
- border -> use border primary
- border-primary -> use border primary
- border-accent -> use border primary
- border-inverted -> use border-white

- [ ] design/adjustments
The figma file needs to be adjusted, adding the outline versions and adding a diviation note (increase border width being 3px but design sticks to the brand specs of 2px). This should be done after the dev implementation in case the developers finds a missed solution to provide 2px width (never loose hope).

## Subtasks
- [x] #1003 
- [x] #1004 
- [x] https://github.com/solid-design-system/figma/issues/171 

## DoR
- [x] Item has business value
- [x] Item all subtasks have been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [x] All subtasks have been closed

**Comment by karlbaumhauer** [comment]
@EllaELSA, @coraliefeil and @yoezlem FYI

@christophsaile do you, by any chance have an idea how to fix it? From what I understand, @abudd1094 is currently blocked in his migration task.

**Comment by abudd1094** [comment]
Please see my comments on the CMS ticket here:
https://jira.apps.union-investment.de/browse/PB2B-10796 

The criteria in that ticket ask for the 5 variants available in `sd-container` for both `stylized=true` and `stylized=false`:
'(default)' | 'primary-100' | 'primary' | 'border-neutral-400' | 'white'

sd-brandshape offers 3 variants which do not even match:
'neutral-100' | 'primary' | 'white'

I need to combine sd-container and sd-brandshape to migrate ui-cms-container (remove ui-container) while maintaining the functionality of the "stylized" prop.  This seems to be a misalignment between the brand design, Solid, and CMS team.  Please advise ASAP, we are indeed blocked.

**Comment by coraliefeil** [comment]
We need all color styles currently shown in sd-brandshape to reuse them in ui-cms-superteaser.

[What we could do is](https://www.figma.com/file/VTztxQ5pWG7ARg8hCX6PfR/Solid-DS-%E2%80%93-Component-Library?type=design&node-id=20570-13997&mode=design&t=GEwhqc7Rht6TDIWA-11)

What do you think @EllaELSA ?

**Comment by abudd1094** [comment]
If it helps, this is the current behavior of `ui-container`which I need to recreate:
https://cms-components.fe.union-investment.de/latest/storybook/index.html?path=/story/cms-components-cms-container--configurable&args=stylized:!true&globals=backgrounds.value:!hex(F6F6F6)

**Comment by abudd1094** [comment]
I don't see border-neutral-400 or primary-100 in the suggestion and don't understand where the additional outlines come from.

<img width="838" alt="image" src="https://github.com/solid-design-system/solid/assets/39494579/7936acbd-5e70-490b-acd0-e342d5b0db1f">
<img width="920" alt="image" src="https://github.com/solid-design-system/solid/assets/39494579/77f6f0d2-ed19-491f-b9dd-627f768298b6">

**Comment by karlbaumhauer** [comment]
@coraliefeil unfortunately we cannot update the sd-brandshape component that easily. We need to figure out a way to make this work in development. the current way does not work with outline-variants.

Lets figure this out in our teams chat.

@abudd1094 we will come back to you with a solution asap. Unfortunately you need to wait for a final decision as one possibility is to create a new component, you would need to use.

**Comment by karlbaumhauer** [comment]
I adopted the description with the information from our pre-refinement today. Ticket will be handled in the refinement on Friday.

**Comment by mariohamann** [comment]
Note from my side: Switching to CSS will change the form of the brandshape significantly:

![CleanShot 2024-03-08 at 12 26 13](https://github.com/solid-design-system/solid/assets/26542182/4bc2a6b0-212e-4ee4-b5b5-2df787bf7b93)

The red in the back shows the CSS solution, the blue in the front is the original shape which we currently use.

**Comment by mariohamann** [comment]
![CleanShot 2024-03-08 at 12 37 25](https://github.com/solid-design-system/solid/assets/26542182/37d3585f-1a52-4f08-990b-c8a1a2a8c46b)

by setting a `filter: drop-shadow(-1px -1px red) drop-shadow(0px -1px red) drop-shadow(1px -1px red) drop-shadow(-1px 0px red) drop-shadow(0px 0px red) drop-shadow(1px 0px red) drop-shadow(-1px 0px red) drop-shadow(0px 1px red) drop-shadow(1px 1px red)` on the whole brandshape, iterating the positions, I was able to fake an outline. Maybe that could work in the end.

**Comment by mariohamann** [comment]
Furthermore it could be worth digging into https://frontendmasters.com/blog/creating-flower-shapes-using-css-mask-trigonometric-functions/ if brand wants to have the brandshape in it's original state.

**Comment by karlbaumhauer** [comment]
> @karlbaumhauer @yoezlem @mariohamann @coraliefeil I got an update from Sandra C. regarding the outline. The 3px feel for her too massive in comparison to the current 1px in magnolia and to the specifications of 2px. If there is currently no other way, then that's the way it is, but she would like to give a mandate to look for another solution in the long term that simply comes closer to the desired look.
> 
> I would leave it with that for now.

@EllaELSA just to be clear. We go the the solution from @mariohamann and keep 3px right? If so, I will open up a ticket for the future to research on a better solution reaching the brand specifications.

**Comment by EllaELSA** [comment]
@karlbaumhauer Yes keep the 3px and have a ticket in backlog that from brand side there is a wish to optimize it to 2px

**Comment by karlbaumhauer** [comment]
@yoezlem I adjusted the description according the brand decision and moved it into the refinement column. 

FYI @abudd1094... in case you finde some time in between, your welcome to take over this solution (as it has become less effort now). In case you have some questions, let me know.

**Comment by van-nguyen-ht** [comment]
[Figma Branch ](https://www.figma.com/file/hjaMuBTzHsYlV7FMm4vLpU/sd-brandshape-image-V.1.0.0?type=design&node-id=8713-2940&mode=design)

**Comment by abudd1094** [comment]
Hey @solid-design-system/core-development @van-nguyen-ht !

Progress looks good.  Our ticket https://jira.apps.union-investment.de/browse/PB2B-10796 has come onto the radar again.  If it's ok for you, I can pick up this Solid ticket and implement it as described.  If that throws off the current Solid sprint, please let me know and I'll try to find another ticket to focus on.

**Comment by abudd1094** [comment]
@karlbaumhauer @solid-design-system/core-development @van-nguyen-ht 

I've had a look again at this ticket, the ui-container migration guide, the CMS ticket for ui-container to sd-container / sd-brandshape, and am unable to proceed.  The criteria do not align and are too unclear to implement.

The expectation as defined by CMS is that we can migrate ui-cms-container to retain the behaviors of ui-container using sd-container style and sd-brandshape.  There we defined 5 color variants which match sd-container.  Below I have listed the defined variants for both container and brandshape.  For ui-cms-container I am not sure how one would align the 5 variants defined for sd-container with the currently available definitions for sd-brandshape.

**5 Variants Defined for sd-container**
(default) (neutral-100) --- Clear
primary --- Clear
white
primary-100
border-neutral-400

**6 Existing and Variants Defined in This Ticket for sd-brandshape**
neutral-100 (exists) --- Clear
primary (exists) --- Clear
white (exists) 
border-primary (newly defined above)
border-white (newly defined above)
image (newly defined above)

**6 Variants Defined in Figma Documentation for sd-brandshape**
neutral-100 --- Clear
primary --- Clear
primary|80
white-100|80
border-white

**Comment by karlbaumhauer** [comment]
@abudd1094 thx for the feedback. The design has its own branch and ticket. I don't know if you have access to this ticket: https://github.com/solid-design-system/figma/issues/171 

Regarding the mismatch between the CMS ticket and our new specs: there might be some adjustments neccessary as we decreased the versions together with brand. So in case you cannot meet all migration requirements, you need to address this in your CMS ticket. These changes have been approved by brand and are mandatory. 

In case you need some further information, pls let me know. In case you start with this ticket, pls assign it to you and change the iteration to the current one (or give me a hint).

**Comment by christophsaile** [comment]
@karlbaumhauer, @yoezlem any updates on this topic? :)

**Comment by yoezlem** [comment]
Branch: https://github.com/solid-design-system/solid/tree/feat/extend-sd-brandshape-variants
