### ISSUE TITLE
docs: 📚 Login/Logout [PSOLIDDS-3]

### ISSUE THREAD

**Issue by coraliefeil** [solid-design-system/solid#902]
## Description

In the IK project, the question arose as to where login/logout buttons/links can be found in the portal. As this is a global issue, we would like to pass the question back to you. Do you already have any ideas/drafts for this?

Login: Header (incl. responsive display) 
Logout: Via header directly? Or via flyout (incl. responsive display) 

[[PSOLIDDS-3]](https://jira.apps.union-investment.de/browse/PSOLIDDS-3)

## Todos

- [ ] Find/collect where teams currently locate this functionalities
- [ ] Consolidate and add guideline to ux pattern

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch
