### ISSUE TITLE
feat: implement sd-footnotes

### ISSUE THREAD

**Issue by christophsaile** [solid-design-system/solid#920]
## Description

Currently the code examples of the sd-footnote docs are missleading:

![grafik](https://github.com/solid-design-system/solid/assets/54807480/73900e8b-c86b-4467-af7f-90beb6908299)
https://solid-design-system.fe.union-investment.de/x.x.x/storybook/?path=/docs/styles-sd-footnote--docs

Should be `<ol><li>...</li></ol>` instead of divs with paragraphs.

**Todo to solve the issue:**
- [x] remove sd-footnote completely (BREAKING CHANGE)
- [ ] change migration guide
- [x] remove --continue from sd-footnotes
- [x] align the indentation to three digits
- [x] ensure that storybook is not overwriting sd-footnotes 

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by mariohamann** [comment]
Oh. That's interesting. And I think you're right. Maybe we should have build this as `<ul class="sd-footnotes"><li>...</li></ul>` and `<ol class="sd-footnotes"><li>...</li></ol>`. What do you think?

**Comment by christophsaile** [comment]
@mariohamann I think thats an good idea. This way not every library user has to disable the default list styles for `<ol>` :)

**Comment by christophsaile** [comment]
Maybe you can also keep the way you do it currently but add an additonal style for the `<ol>, <ul>` because of the reason i mentioned above

**Comment by mariohamann** [comment]
I'm currently trying out something. @christophsaile could you read through these docs here https://64469bd84c5ea1ce2dd5d016-mfbzavcbfx.chromatic.com/?path=/docs/styles-sd-footnotes--docs, insert the following CSS on your side and give it a try if this is what you need?

```css

.sd-footnotes {
    font-size: var(--sd-font-size-sm, .875rem);
    text-align: left;
    --tw-text-opacity: 1;
    color:rgb(var(--sd-color-neutral-700, 104 104 104)/var(--tw-text-opacity))
}

.sd-footnotes:is(ol) li {
    counter-increment: list-item;
    display: flex;
    gap:var(--sd-spacing-2, .5rem)
}

.sd-footnotes:is(ol) li:before {
    content: counter(list-item);
    font-size: 10px;
    line-height: var(--sd-line-height-normal, 150%);
    padding-top: 1px;
    width:var(--sd-spacing-5, 1.25rem)
}

.sd-footnotes:is(ol).sd-footnotes--continue {
    counter-increment:footnotes-continue 0
}

.sd-footnotes:is(ol).sd-footnotes--continue li {
    counter-increment:footnotes-continue
}

.sd-footnotes:is(ol).sd-footnotes--continue li:before {
    content:counter(footnotes-continue)
}

.sd-footnotes:is(ul) {
    list-style: ""
}

.sd-footnotes--inverted {
    --tw-text-opacity: 1;
    color:rgb(var(--sd-color-white, 255 255 255)/var(--tw-text-opacity))
}
```

**Comment by christophsaile** [comment]
@mariohamann the continue option seems not to work in firefox. This feature is not needed in the cms because the starting index can be set by the editor.
But there is one issue regarding the spacings. 
In our setup the spacings seem to be a bit different.
left = solid, right = cms
![grafik](https://github.com/solid-design-system/solid/assets/54807480/c1adb148-884a-4a84-8c81-549a83b0afcc)

**Comment by Vahid1919** [comment]
As per my eye test, the footnote number has similar heights outside Storybook as well: https://codepen.io/Vahid-Nesro/pen/ZEPqdMJ
