### ISSUE TITLE
docs: 📚 deprecate `ui-surrounding-map`

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#944]
## Description
As the `ui-surrounding-map` will not be provided as a component (see #308), the component needs to be added to the discontinued list and a migration guide, which explains the usage of the [Google Maps Style Wizzard](https://mapstyle.withgoogle.com/) in combination with #573, should be written.

## Todos

- [x] Design: formulate a design guide on how to use the wizzard and what design expects from users (use default and under which circumstances to change it) => add in this ticket as a comment. @van-nguyen-ht 
- [x] Development: create the migration guide on GitHub and add the explanation to it.
- [x] Development: add the `ui-surrounding-map` to the discontinued list in the migration guide intro

## Where to put the documentation
GiHub/Storybook/Figma
## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by van-nguyen-ht** [comment]
![Screenshot 2024-04-23 at 18 15 10](https://github.com/solid-design-system/solid/assets/118520877/2fab2747-f592-4695-872f-25279d382cb3)

Users can use [Google Maps Style Wizzard](https://mapstyle.withgoogle.com/) in Standard theme to customize view option.  Due to brand preference to maintain UI look and feel, customisation factors should be adjusted with consideration, extreme styling (i.e.: Retro) should be avoided. 

Map marker component can be used to mark a specific location with content. The map markers come in two different options: Main marker & Place marker

**Comment by karlbaumhauer** [comment]
thx @van-nguyen-ht 

@yoezlem I put this into refinement correct?

**Comment by van-nguyen-ht** [comment]
@coraliefeil can you have a look at the text if sth should be added? Thank you

**Comment by coraliefeil** [comment]
I added the styling info to [figma](https://www.figma.com/design/VTztxQ5pWG7ARg8hCX6PfR/Solid-DS-%E2%80%93-Component-Library?node-id=21641-5787&t=K07oLckkTb47sdrx-11)
